### ISSUE TITLE
MySqlDbBind添加无符号支持

### ISSUE THREAD

**Issue by yedajiang44** [donet5/SqlSugar#1000]
现在的dbfirst动态建表时不支持mysql的所有无符号类型，查看了下[MySqlDbBind](https://github.com/donet5/SqlSugar/blob/bf218a56a07d140a34568d42b606a429f1698bf3/Src/Asp.Net/SqlSugar/Realization/MySql/DbBind/MySqlDbBind.cs)仅仅处理了有符号类型

**Comment by donet5** [comment]
dbfirst是生成实体，  codefirst才是建表， 具体是什么问题

**Comment by yedajiang44** [comment]
> dbfirst是生成实体，  codefirst才是建表， 具体是什么问题

表中字段是无符号，用dbfirst生成的实体是有符号的，而且用sqlsugar获取表中字段时，也是有符号，我想用sqlsugar获取已有的表字段，然后动态建表，只是表名不一样，但是由于获取的列类型全是有符号，导致生成的表不符合要求

**Comment by donet5** [comment]
具体是哪个方法有问题 ，没听懂

**Comment by donet5** [comment]
是否有符号，可以自个处理一下吧，目前获取表信息方法没有符号这个字段，比如字段名U开头带表有符号，获者写个SQL专门查一下是否有符号

**Comment by donet5** [comment]
后面版本我想办法优化一下

**Comment by donet5** [comment]
GetColumnInfosByTableName 添加了IsUnsigned 字段  ，源码更新过了

**Comment by donet5** [comment]
有问题发新贴

**Comment by yedajiang44** [comment]
非常感谢！下午抽空试一下。
