### ISSUE TITLE
MySQL数据库事务隔离级别

### ISSUE THREAD

**Issue by sunyu005** [donet5/SqlSugar#1002]
你好，

多库场景 SqlSugarScope.BeginTran() 事务开启，使用的事务隔离级别是什么？

发生现象是：对同一个表一个事务内两次查询，第一次查询执行后，手动改了数据库的这条数据，第二次查询到的结果还是第一次查询的结果。

是事务隔离级别导致发生这种现象的吗？

MySQL数据库的隔离级别是：
![2022-03-21_191542](https://user-images.githubusercontent.com/48470418/159252469-4dd03298-0458-4590-8471-3a2abfcc6491.png)

**Comment by donet5** [comment]
```cs
var mysqlDb = db.GetConnection("mysql");
 var mssqlDb = db.GetConnection("mssql");
 try
 {
        mysqlDb.Ado.BeginTran(IsolationLevel.ReadCommitted);//开启库1的事务
        mssqlDb.Ado.BeginTran(IsolationLevel.ReadCommitted);//开启库2的事务
                 
         //业务代码 只能用  mysqlDb和 mssqlDb 
 
        db.CommitTran();//注意不能用db.ado.CommitTran
 }
 catch (Exception ex)
 {
        db.RollbackTran();
        throw ex;
}
```

**Comment by donet5** [comment]
上面的代码可以设置隔离级别

**Comment by donet5** [comment]
db.ContextId看一下是否是同一个DB 不然就不是一个上下文 ，事务也不会生效

**Comment by sunyu005** [comment]
是同一个ContextId，试了一下一个事务里只有一次查询，在查询之前打了断点，然后改数据，查询的结果就是修改后的数据。

怀疑是不是第二次查询的是第一次查询操作的缓存？

**Comment by sunyu005** [comment]
把数据库的事务隔离级别设置为：read-committed

![2022-03-22_180619](https://user-images.githubusercontent.com/48470418/159456847-409aad4b-0e00-46f3-881b-f36ef41bff85.png)

**Comment by donet5** [comment]
ORM查询没有缓存的

**Comment by sunyu005** [comment]
那就很奇怪，相同的操作用mysql命令去执行，是可以查到更新的数据的。
然后我有用SQL server数据库试了一下，代码没动，也是正常的。

**Comment by donet5** [comment]
```cs
            var q = db.Queryable<Order>().First();
            q.Name = "a1";
            //update all columns by primary key
            var result = db.Updateable(q).ExecuteCommand();//update single
               q = db.Queryable<Order>().First();
            db.CommitTran();

```
打断点调试 q的值变了  ，没有出现你反馈问题

**Comment by sunyu005** [comment]
更新和查询是两个事务，在执行第二个查询前打断点。执行更新操作提交事务，然后执行第二个查询，会发现还是第一次的查询结果。数据库事务是readcommited，代码没设置事务隔离级别，应该是执行的数据库的事务吧。
