### ISSUE TITLE
ExecuteReturnSnowflakeId() 雪花Id重复

### ISSUE THREAD

**Issue by itcsdnnet** [donet5/SqlSugar#1003]
在执行GetInstance().Insertable(recordSetp).SplitTable().ExecuteReturnSnowflakeId();时异常，报错信息为：Duplicate entry '1506490376863612928' for key 'PRIMARY'主键冲突
详细异常：   at SqlSugar.SplitInsertable`1.ExecuteReturnSnowflakeIdList()\r\n   at SqlSugar.SplitInsertable`1.ExecuteReturnSnowflakeId()\r\n   at ……
程序入口已加入：SnowFlakeSingle.WorkId = StringExtend.ToInt(ConfigurationHelper.GetConfigValueByKey("Config:snowFlakeWorkId"));

**Comment by donet5** [comment]
雪花ID出现重复只有2种情况
1 服务器修改过时间  （设置WORKID 可以防止冲突）
2. 多台服务器插入  （不同服务器设置不同的workID）

**Comment by itcsdnnet** [comment]
> 雪花ID出现重复只有2种情况 1 服务器修改过时间 （设置WORKID 可以防止冲突） 2. 多台服务器插入 （不同服务器设置不同的workID）

1. 服务器采用自动获取，没有更改过时间
2. 采用的是同一台服务器不同应用，已在程序入口指定了SnowFlakeSingle.WorkId = 1;

**Comment by donet5** [comment]
更新workid在观察一些时间看看， 这个算法单服务器上百亿也没能有重复数据出现

**Comment by donet5** [comment]
检查你这个list 对象有没有多处使用， new list 插入，不要一个list多次使用

**Comment by donet5** [comment]
如果还有问题，写个重现DEMO发我

**Comment by donet5** [comment]
如果还有问题，写个重现DEMO发我
