### ISSUE TITLE
Where queryable error (Ambiguous match found.)

### ISSUE THREAD

**Issue by mrreddevil2412** [donet5/SqlSugar#1006]
I use where queryable with column (varchar) then response error (Ambiguous match found), 
but i use column ID(int) then none error

my code:
![image](https://user-images.githubusercontent.com/30259651/160971728-a59e3074-a2fa-4274-a349-6663dcc06317.png)

**Comment by donet5** [comment]
database  is  varchar?

**Comment by donet5** [comment]
var id=model.RecordId;
Where(o.guid==id)     try it

**Comment by mrreddevil2412** [comment]
> var id=model.RecordId; Where(o.guid==id) try it

yep, i tried, it work

**Comment by donet5** [comment]
Can you send me the realization of model  entity for a look

**Comment by donet5** [comment]
It should be caused by a special entity property

**Comment by mrreddevil2412** [comment]
> Can you send me the realization of model entity for a look

 public class DefaultModel
    {
        private int _pageIndex;

        public int PageIndex
        {
            get => _pageIndex;
            set => _pageIndex = value - 1;
        }

        public int PageSize { get; set; } = 20;

        public int TotalRecord { get; set; }

        public string Sort { get; set; }

        public int RecordID { get; set; }
    }
