### ISSUE TITLE
Insert or Saveable If Not exist any column

### ISSUE THREAD

**Issue by mrreddevil2412** [donet5/SqlSugar#1010]
I can't find the document, saveable or insert data to sql.
With IF NOT EXIST(sql query)
Before save or insert need check row existence with codition 
EX (SQL query):
 IF NOT EXIST( SELECT o.Id FROM Table_Name where o.Id=1)
 BEGiN 
 insert or update
 END
 
 Sorry, my english is bad!

![image](https://user-images.githubusercontent.com/30259651/162152596-bd0374dc-04c7-4871-95d0-59211bf9e810.png)

**Comment by donet5** [comment]
Db.Storageable(list2).ExecuteCommand()// 5.0.6.4

**Comment by donet5** [comment]
https://www.donet5.com/Home/Doc?typeId=2353

**Comment by donet5** [comment]
https://www.donet5.com/Home/Doc?typeId=1208
