### ISSUE TITLE
oracle backup database like sqlserver

### ISSUE THREAD

**Issue by wenbei421** [donet5/SqlSugar#1011]
https://github.com/donet5/SqlSugar/blob/185e89d7d671754ed40d84c470b093e70a7aad91/Src/Asp.Net/SqlSugar/Realization/Oracle/DbMaintenance/OracleDbMaintenance.cs#L110

**Comment by donet5** [comment]
OK

**Comment by donet5** [comment]
ORACLE   USE master;BACKUP DATABASE {0} TO disk = '{1}'        Have you tested it?

**Comment by donet5** [comment]
Oracle no support backup  ，you can pull
