### ISSUE TITLE
WithCache Not Run

### ISSUE THREAD

**Issue by mrreddevil2412** [donet5/SqlSugar#1013]
Hi!
Once again I'm bothering you.
I have read the caching documentation and followed the instructions exactly.
But when I query and monitor using SQL Server Profiler
I still see query executed from SQL. Although I used withCache(1000).
I don't understand why using caching but still querying from sql?
Config :
![image](https://user-images.githubusercontent.com/30259651/163434351-cfbcbfeb-2ef6-4f2a-9dc7-ba97c376865b.png)

SugarQuery C#:
![image](https://user-images.githubusercontent.com/30259651/163434675-a8a07c1a-39ad-410a-897d-bb8b79f663cc.png)

SQLSV Profiler:
![image](https://user-images.githubusercontent.com/30259651/163434095-263d13b4-f7db-48d3-9aec-7f519f450246.png)

**Comment by donet5** [comment]
It is cached according to SQL + parameters. Your generated keys will be different, so it is not suitable for caching

**Comment by donet5** [comment]
It is suitable for queries with write dead conditions

**Comment by donet5** [comment]
It is suitable for fixed condition query or full table query

**Comment by mrreddevil2412** [comment]
So can I create a key according to the condition?

**Comment by donet5** [comment]
if (db.DataCache.Get<Order>("key_表名") == null)
 {
        var list=db.Queryable<Order>().ToList();
        db.DataCache.Add("key_order",list);
         return list;
  }
  else
  {
         return db.DataCache.Get<Order>("key_表名");
  }

**Comment by donet5** [comment]
if (db.DataCache.Get<Order>("key_表名") == null)
 {
        var list=db.Queryable<Order>().ToList();
        db.DataCache.Add("key_order",list);
         return list;
  }
  else
  {
         return db.DataCache.Get<Order>("key_表名");
  }

**Comment by donet5** [comment]
For conditional queries, this caching makes little sense

**Comment by mrreddevil2412** [comment]
I love it! 
Thanks bro!!!!!!!!!!!!!!
