### ISSUE TITLE
实体与表映射出错。从“Double”到“DateTime”的强制转换无效 

### ISSUE THREAD

**Issue by ZYT5ting** [donet5/SqlSugar#1015]
数据库内Datetime类型保存的是unix时间戳，即long（占8字符），而不是text（精确到秒数占19字符）。
请问sqlsugar支持时间戳转datetime吗？
用时间戳保存Datetime类型，相较于text存储空间要小很多。

**Comment by donet5** [comment]
什么数据库给个Long的用例

**Comment by ZYT5ting** [comment]
数据库：Sqlite
测试文件：链接：https://pan.baidu.com/s/1FgPAW8NoSqZOCwDTmR-NDg  提取码：575q
测试字段：test.time1，test.time2 类型DATETIME，数据存储格式： NUMERIC
SQLite Expert Professional 设置DATETIME存储方式：Options- Data- Date/Time如下：
![image](https://user-images.githubusercontent.com/43063179/164163654-f3165dfb-7c17-4373-b481-d53251bb9ce8.png)

时间数据查询后：
![image](https://user-images.githubusercontent.com/43063179/164164101-cba18ba9-32d2-4554-9984-bac903eb51eb.png)

SQLite是动态数据类型，如果不设置DATETIME 而是用NUMERIC类型，则不能在数据库内直观看到时间，需要程序转换才能看到时间。

> 什么数据库给个Long的用例

**Comment by donet5** [comment]
好的我抽空看一下

**Comment by ZYT5ting** [comment]
> 好的我抽空看一下

感谢大神!!

**Comment by donet5** [comment]
这个暂时不好处理, 建议用long 类型 你序列化的时候加个特性 转成时间
1、驱动读的是long你转的是datetime肯定是报错 除非加 value.gettype()去验证这样全局处理性能大大降低 会影响其他
2、条件过滤也不好处理 ，你字段是和数据库是datetime你的实体了是datetime你数据库存的是数字肯定有问题
