### ISSUE TITLE
Use Ado begintran() Error =>The connection does not support MultipleActiveResultSets.

### ISSUE THREAD

**Issue by mrreddevil2412** [donet5/SqlSugar#1016]
Hi ^^
My project use 2 db.
When I use begintran()
update 
ComitTran()
Error result: > The connection does not support MultipleActiveResultSets.

![image](https://user-images.githubusercontent.com/30259651/165206831-5aaa2dce-27ea-4bc8-b990-d332e79ea5f1.png)

**Comment by donet5** [comment]
need  await   _db.XXXX.xxxAsync();

**Comment by mrreddevil2412** [comment]
What your Name ^^
Thank you for everything

**Comment by donet5** [comment]
My name is sugar
