### ISSUE TITLE
導航查詢>主表過濾功能的 Any() 

### ISSUE THREAD

**Issue by eukaryoteoops** [donet5/SqlSugar#1017]
語法
`await _db.Queryable<Videos>().Includes(o => o.Tags).Where(o => o.Tags.Any(z => z.Id == 1))`
Entity設定
`[Navigate(typeof(VideoTagMapping), nameof(VideoTagMapping.VideoId), nameof(VideoTagMapping.TagId))]
        public List<VideoTags> Tags { get; set; }`
想將tags裡面id=1的Video資料撈出
卻拋出id column不存在的錯誤
列出sql發現
1 .子查詢`VideoTags_1.`Id` in` 應該要select TagId 且 where VideoId = o.Cid 才對，看起來相反
2. AND ( `Id` = @id0 ) 應該要包在子查詢裡面，看起來被放在主表那層，而主表無Id欄位

`SELECT Count(*) FROM `Videos` o  WHERE  
( 
  ( 
    (
      select count(1) from `VideoTags` VideoTags_1  where  VideoTags_1.`Id` in (select `VideoId` from `VideoTagMapping` where `TagId` = o.`Cid` )
	)  
    AND ( `Id` = @id0 )
  ) >0 
)`

能幫忙釐清嗎

**Comment by donet5** [comment]
源码应该更新过了 ，你可以NUGET安装预览版本 5.0.7.7 previrew03

**Comment by eukaryoteoops** [comment]
正常了 感謝
