### ISSUE TITLE
查询会忽略部分字段的bug

### ISSUE THREAD

**Issue by bbhxwl** [donet5/SqlSugar#1018]
我联表查询，有一个表的有一个字段，我看生成的sql代码也没有。
大概是这样，我在一个公共库建的一个class，
然后里面有个List<自定义类> 的属性，我没直接在标记设置isjson，而是在
ConfigureExternalServices里面判断是不是这个类型，然后设置的
column.IsJson = true;
在这种情况下，我左联查的，就像下面z这样，所有字段都查出来了。只有那个没在标记就写isJson的，生成的sql里面也没有。然后我把class没在单独的项目里面写，写在本项目了，然后标记也写IsJson了。就可以查到了。不知道具体是因为class在其他库里面，还是说没在标记就写IsJson的问题。
![image](https://user-images.githubusercontent.com/26525599/167240014-aaec5bf8-605b-4524-b174-2523f718c085.png)

**Comment by donet5** [comment]
收到，我这边会尽快和你确认

**Comment by donet5** [comment]
源码更新过了，你可以先用源码编译个DLL先用
