### ISSUE TITLE
有办法联表查询忽略不查某个字段么

### ISSUE THREAD

**Issue by bbhxwl** [donet5/SqlSugar#1020]
我看更新有可以忽略某个字段，查询有么。我又个字短里面存的byte[]，大概1kb，不想联表都查出来。

**Comment by donet5** [comment]
实体方式更新  有 IgnoreColumns(x=>x.xx)

**Comment by donet5** [comment]
你可以这样写 db.Queryable( db.queryable<T>().IgnoreColum(x=>x.xxx)) .LeftJoin

**Comment by donet5** [comment]
var queryableRight=db.queryable().IgnoreColum(x=>x.xxx);
db.queryable<T>().LeftJoin(queryableRight,(t1,t2)=>xxx)

**Comment by bbhxwl** [comment]
> 

这样是生成一条sql代码是吧，不是两次是吧。

**Comment by donet5** [comment]
一条SQL

**Comment by donet5** [comment]
还有疑问吗
