### ISSUE TITLE
sqlsugarCore 对sqlite 支持真的是很不全面，使用corefirst完全不能用，

### ISSUE THREAD

**Issue by wz172** [donet5/SqlSugar#1023]
不能够使用corefirst创建数据库，创建表，进行数据迁移。
SQLsugar 5.0.8
sqlite版本： Microsoft.Data.Sqlite.Core 5.0.8

 private void InitBaseInfo()
        {
            if (!File.Exists(CurDataPath))
            {
                using (File.Create(CurDataPath)) { };
                DbContext.DbMaintenance.CreateDatabase();
            }
            string sql = "SELECT name FROM sqlite_master WHERE type='table'";
            var reader = DbContext.Ado.GetDataReader(sql);
            List<string> tableNames = new List<string>();
            while (reader.Read())
            {
                tableNames.Add(reader.GetString(0));
            }
            if (!tableNames.Contains(nameof(StorageMessageModel)))
            {
                DbContext.CodeFirst.InitTables<StorageMessageModel>();
            }
        }

上面是为了创建数据库，貌似不能够创建

**Comment by donet5** [comment]
下源这个源码学习一下  https://github.com/donet5/WebFirst  这个就是用sqlusgar自动建库建表的项目

**Comment by donet5** [comment]
https://www.donet5.com/_theme/ueditor/utf8-net/net/upload/file/20210109/6374581344940192419206684.rar   或者下载这个DEMO 这个更简单

**Comment by donet5** [comment]
长时间没反馈先关闭，有问题重新发贴
