### ISSUE TITLE
MySQL8 , SqlSugarCore5.0.8 。AddColumnRemark报错。

### ISSUE THREAD

**Issue by jiaCheng-Yu** [donet5/SqlSugar#1024]
CodeFirst可以生成数据表，但无法给每个字段添加字段注释信息。MySQL8 , SqlSugarCore5.0.8。

**Comment by donet5** [comment]
只前只能支持这个重载  public override bool AddRemark(EntityInfo entity)  通过实体加上备注， 因为有技术难度 mysql不支持直接修改备注只能通过例的方式 ，我想办法支持一下

**Comment by donet5** [comment]
源码进行了更新，优化了错误提示，并且错误提示给出如何实现的方式
