### ISSUE TITLE
带约束的泛型无法正确解析成Sql

### ISSUE THREAD

**Issue by cjzZZZzzz** [donet5/SqlSugar#1028]
环境:core
版本:5.0.8.1

`

        SqlSugarClient client = new SqlSugarClient(new ConnectionConfig { DbType = DbType.SqlServer });

        public void JoinTest()
        {
            Join<AuthDO>();
        }

        public void Join<T>() where T : IUserLink
        {
            var a = client
                .Queryable<UserDO, T>((u, a) => new JoinQueryInfos(JoinType.Inner, u.Id == a.UserId))
                .Where((u, a) => u.Id == 1)
                .Select((u, a) => a);
        }

        public interface IUserLink
        {
            public int UserId { get; set; }
        }

        public class UserDO
        {
            public int Id { get; set; }
        }

        public class AuthDO : IUserLink
        {
            public int UserId { get; set; }

            public int ObjId { get; set; }
        }

异常

SqlSugar.SqlSugarException : 中文提示 : 当前表达式Convert(a, IUserLink).UserId 不支持，查看导航是否配置正确等English Message : Convert(a, IUserLink).UserIdno support

带约束的表达式会自动加一个Convert(a, IUserLink),需要处理一下

**Comment by donet5** [comment]
收到近期会处理

**Comment by donet5** [comment]
源码已经修复
