### ISSUE TITLE
连接sqlserver 自定义端口 提示 Keyword not supported: 'port'

### ISSUE THREAD

**Issue by Tenodec** [donet5/SqlSugar#1029]
**连接字符串：**
server=xxx;port=1000;uid=xxx;pwd=xxxxx.;database=xxxx
**报错**
连接数据库过程中发生错误，检查服务器是否正常连接字符串是否正确，实在找不到原因请先Google错误信息：Keyword not supported: 'port'..

**Comment by donet5** [comment]
https://www.donet5.com/ask/9/16058
