### ISSUE TITLE
数据过滤器为什么设计为循环字段的次数

### ISSUE THREAD

**Issue by lysilver** [donet5/SqlSugar#1031]
![image](https://user-images.githubusercontent.com/44791098/170862799-fcf2f7d1-1b3d-46c5-aae3-3fb4e5613e77.png)

数据100条，字段30个，循环次数100*30，性能如何保证

**Comment by donet5** [comment]
请给出00*30所花费的时间 和你理想的 时间

**Comment by donet5** [comment]
1000条4个字段  加上插入 sqlserver我的测试时间在 200 毫秒

**Comment by donet5** [comment]
实际损耗很小

**Comment by lysilver** [comment]
> 实际损耗很小

还有其它的操作啊，根据特性进行数据脱敏，审计，现在只能通过缓存减少获取特性的次数

**Comment by donet5** [comment]
你如果在这里面写复杂逻辑肯定是不行的，一般这个地方就是处理默认值问题的，比创建时间给个DateTime.Now

**Comment by donet5** [comment]
你可以写出具体慢的例，我看能不能帮你优化一下

**Comment by lysilver** [comment]
![image](https://user-images.githubusercontent.com/44791098/170902506-f7c98339-4d42-45f1-98e3-f18f6ceba63b.png)

```csharp
var attributes = propertyInfo.GetCustomAttributes(typeof(UpdateByAttribute), false);
```

主要是为了抹平不同orm的差异， 现在是通过进来之后缓存找到的字段，或者DataFilterModel给个字段的索引，根据索引判断执行的次数

**Comment by donet5** [comment]
你要想每条数据只执行一次的事件吗

**Comment by donet5** [comment]
db.Aop.DataExecuting = (exp,o) =>//SQL execution error event
            {
                if (o.EntityColumnInfo.IsPrimarykey) 
                {
                  //这样每条记录就只执行一次，而不是从细的字段处理
                }
            };

**Comment by lysilver** [comment]
> 只执行一次的事件吗

是的

**Comment by donet5** [comment]
上面的方案可以解决你的问题了吗，通过主键验证

**Comment by lysilver** [comment]
> 上面的方案可以解决你的问题了吗，通过主键验证

可以是可以， 1000*30 次循环  1000次循环 这个哪怕是空循环，通过基准测试也有44倍左右的性能差距

**Comment by donet5** [comment]
可以提供测试代码

**Comment by donet5** [comment]
610262374@qq.com

**Comment by lysilver** [comment]
> 可以提供测试代码

![image](https://user-images.githubusercontent.com/44791098/171114726-306596a4-3a09-48e6-84f1-9acf08383bc4.png)

我这个只是基准测试，没有对DataExecuting进行测试

**Comment by lysilver** [comment]
> 你这个算法还是有有问题的 Enuerable.Range固定的不是一直创建的

代码说的是1000次循环  1000*30循环的效率问题  这根本不需要比较啊

**Comment by donet5** [comment]
`private static void Orm()
{
    var dt = DateTime.Now;
    var chids = Enumerable.Range(1, 40);
    foreach (var item in Enumerable.Range(1, 2000))
    {
        System.Threading.Thread.Sleep(1);
        foreach (var ch in chids)
        {

        }
    }
    Console.WriteLine((DateTime.Now - dt).TotalSeconds);
}
private static void Orm2()
{
    var dt = DateTime.Now;
    foreach (var item in Enumerable.Range(1, 2000))
    {
            System.Threading.Thread.Sleep(1);
        }
    Console.WriteLine((DateTime.Now - dt).TotalSeconds);
}`

**Comment by donet5** [comment]
测试结果是一样的

**Comment by donet5** [comment]
```
private static void Orm()
{
    var dt = DateTime.Now;
    var chids = Enumerable.Range(1, 40);
    foreach (var item in Enumerable.Range(1, 2000))
    {
 
        foreach (var ch in chids)
        {

        }
    }
    Console.WriteLine((DateTime.Now - dt).TotalSeconds);
}
private static void Orm2()
{
    var dt = DateTime.Now;
    foreach (var item in Enumerable.Range(1, 2000))
    {
           
        }
    Console.WriteLine((DateTime.Now - dt).TotalSeconds);
}
```

**Comment by donet5** [comment]
你发的用例 错在 Enumerable.Range(1, 40) 扔在循环里面了，这个应该是在循环外面的

**Comment by lysilver** [comment]
> 你发的用例 错在 Enumerable.Range(1, 40) 扔在循环里面了，这个应该是在循环外面的

![image](https://user-images.githubusercontent.com/44791098/171121783-061d0e70-ffbc-46cf-ae03-cf8ed5eb4bd9.png)

**Comment by donet5** [comment]
我这边测试下2层循环快过1层循环，不是软件怎么设计的

**Comment by lysilver** [comment]
> 我这边测试下2层循环快过1层循环，不是软件怎么设计的

这是新的代码测试的

**Comment by donet5** [comment]
2000条40列 执行时间 2层循环 平均速度在 0.003秒 ， 你算2000插入数据库执行时间 这个性能几乎可以忽略

**Comment by donet5** [comment]
我知道，你要算上循环损耗和数据库执行 性能占比 ，因为比例太小了

**Comment by lysilver** [comment]
> 争这个没什么意义，因为我样设置的AOP更加灵活，可以做到列级别的处理

传入10列所有不能处理列吗

**Comment by donet5** [comment]
ColumInfo有主键 有列名，有备就 ，你那个还要反射

**Comment by donet5** [comment]
你算上反射的时间未必比我这个快
