### ISSUE TITLE
SqlQueryable方法在5.0.6.4以上版本MySQL报Every derived table must have错误

### ISSUE THREAD

**Issue by dongxin** [donet5/SqlSugar#1034]
问题如标题所示，尝试在SqlQueryable方法后使用As方法重命名无效，并得到一个新错误，提示让我使用As方法！即便我已经尝试As方法的带泛型与不带范学的，同样为该错误！

**Comment by dongxin** [comment]
var db = DbScoped.SugarScope;
var result = db.SqlQueryable<AccountInfo>("SELECT * FROM t_account")
    .InnerJoin<OrgInfo>((acc, org) => acc.oid == org.id)
    .Where(acc => acc.id == "1000000009")
    .Select((acc, org) => new AccountDetail
    { 
        id = acc.id.SelectAll(),
        org = org
    }).ToArray()
具体代码就是这样

**Comment by donet5** [comment]
源码已修复 ，一会发布NUGET
