### ISSUE TITLE
SQLServer对Bit类型语句在case when时没做转换

### ISSUE THREAD

**Issue by aqianger** [donet5/SqlSugar#1035]
Select(b=> new
                {
                    IsRunning =  b.IsRunning ? 1 : 0,
                }) 转换出的sql语句是
 WHEN [b].[isrunning] THEN @MethodConst1  ELSE @MethodConst2 END

**Comment by donet5** [comment]
生成的SQL没有错误，描述在清楚一些

**Comment by donet5** [comment]
IsRunning = b.IsRunning ? true : false   这样试试

**Comment by donet5** [comment]
IsRunning = b.IsRunning
或者
IsRunning = b.IsRunning==true?0:1

**Comment by aqianger** [comment]
IsRunning = b.IsRunning==true?0:1 可以

**Comment by donet5** [comment]
源码已经支持 ，NUGET 预计在 5.0.9.1 版本支持
