### ISSUE TITLE
数据插入慢的问题

### ISSUE THREAD

**Issue by tansar** [donet5/SqlSugar#1037]
虽然测试完后你有很大的意见，但同样作为开源作者，还是给你提一下issues 用于改进sqlsugar
1.建议改进常规插入时所有生成的SQL语句一起执行的问题 建议按行*列的单元方式 分包执行性能将会有很大提升
2.bulkCopy数据插入时由于没有做自动分包插入列多时和记录多时将会有性能问题
3.mysql下由于没有分包导致5W条左右的常规插入就会报错（因为mysql本身对sql文档大小做了限制）

如果能改进这三个点sqlsugar性能将会有质的提升

**Comment by donet5** [comment]
```
//(1)、非参数化插入（防注入） 
//优点：综合性能比较平均，列少1万条也不慢，属于万金油写法,不加事务情况下部分库有失败回滚机质
//缺点：最新版本暂无
db.Insertable(List<实体>).ExecuteCommand()  
 
 
//(2)、使用参数化内部分页插入
//优点：500条以下速度最快，兼容所有类型和emoji 
//缺点：500以上就开始慢了 （Oracle中500以上性能比第一种强），要加事务才能回滚 
db.Insertable(List<实体>).UseParameter().ExecuteCommand()//5.0.3.8-Preview及以上版本支持（NUGET搜索勾上包括预览）
 
 
//(3)、大数据写入（特色功能：大数据处理上比所有框架都要快30%）
//优点：1000条以上性能无敌手
//缺点：不支持数据库默认值， API功能简单， 小数据量并发执行不如普通插入，插入数据越大越适合用这个
//新功能 5.0.44
db.Fastest<RealmAuctionDatum>().BulkCopy(GetList());//MySql连接字符串要加AllowLoadLocalInfile=true
```

**Comment by donet5** [comment]
你说的分包方式本身就有

**Comment by donet5** [comment]
/如果数据库现有数据比较多出现比较慢，这个时候可以试试分页
db.Fastest<Order>().PageSize(300000).BulkCopy(insertObjs);

**Comment by donet5** [comment]
只能说你对SQLSUGAR跟本不了解

**Comment by donet5** [comment]
用户不想分包你底层就分包吗？ 你是不处理事务，还是强行加事务，这样做对用户是不透明的

**Comment by donet5** [comment]
就比如MYSQL 普通插入大于5W条报错，用户看不懂错误提示，改个配置就支持了吗？ 或者直接用BULKCOPY

**Comment by tansar** [comment]
随你呀， 我是已经提出问题了， 你不改是你的事，死鸭子嘴硬， 你可以改，不过我们持续关注你的代码， 如果你不同意我的issues 又悄悄改了， 就看得出来你是有多么的虚伪，

你那个自定分包就是个坑， 用户是不知道多大才是最合适的。

大于5W条 报这样的低真提低级错误。。 还要用户自己去处理。
![image](https://user-images.githubusercontent.com/12521832/175437440-5d8e0231-ebe7-4991-a36a-a21ac6d88058.png)

我会持续关注 我铁定你会悄悄改。

**Comment by tansar** [comment]
如果你不改这个分包机制 你的性能比不上hisql 5-100W 间任意数据量段都比不上，还说是吊打所有框架，提了改进都不改，还好意思说吊打所有ORM框架 
.
![image](https://user-images.githubusercontent.com/12521832/175438215-ddf740f8-2c21-4369-9ef6-eb114001ba26.png)

以后吹牛前注意一下。

**Comment by tansar** [comment]
如果发现hisql的bug 欢迎提issues 我会虚心接受

**Comment by tansar** [comment]
别说我黑你，是你黑别人
https://www.donet5.com/home/doc?masterId=1&typeId=1191
https://www.donet5.com/home/doc?masterId=1&typeId=2404

![image](https://user-images.githubusercontent.com/12521832/175438388-27c2a37b-bff7-4c2e-9f04-9985876544bc.png)
![image](https://user-images.githubusercontent.com/12521832/175438445-d157d1c1-f53d-4c25-8e67-d3e91cbab9e9.png)
