### ISSUE TITLE
postgresql 表的大小写问题  

### ISSUE THREAD

**Issue by tansar** [donet5/SqlSugar#1038]
postgresql 大小写问题未默认处理
![image](https://user-images.githubusercontent.com/12521832/175437764-b4111808-1805-4eba-b8b7-1221d04a1ee3.png)

代码重现
https://github.com/tansar/HiSqlTestDemo

发现开源软件的bug 义务型的提交issues ，改不改由你自己决定
提的数据插入慢的问题不解决 直接关闭ISSUES 真牛

**Comment by donet5** [comment]
![A~E1MR{AF{ Y` %0461_~1X](https://user-images.githubusercontent.com/12455385/175492964-b2aeac82-055c-449e-b3dc-478af601b338.jpg)
我都不知道你怎么好意思说我的框架慢的，你可以喧传你的ORM但是请求要拿我来蹭热度，我要是用户实际需求 ，到于你连PGSQL规范和不规范表用法都不知道，你认为是BUG只是没配置或者你默认配置是非规范表

**Comment by donet5** [comment]
![image](https://user-images.githubusercontent.com/12455385/175493568-6dafcd70-8df3-402d-bd07-614065a5d8a2.png)

**Comment by tansar** [comment]
可能在你的电脑上不用80秒， 但是SQLSUGAR  就是最后一名， 这是不争的事实

**Comment by donet5** [comment]
![image](https://user-images.githubusercontent.com/12455385/175501247-23842cd4-f764-452f-b4ed-5166def57f1f.png)

**Comment by donet5** [comment]
我都不好意思说 ，用户都看不下去了

**Comment by tansar** [comment]
我只能说你的网络打手好多，你换CORE版本， 通过nuget安装的标准版 谁还会管指定版本， 你的包大小都是要手动指定的， 跑出来的结果有啥意义 ， 拉挎就算了 ，还嘴硬的要死

**Comment by tansar** [comment]
这个issues 我提的是你的BUG ， 你就扯别的， 还关闭了issues ，

**Comment by tansar** [comment]
坐等你悄悄改， 虚伪的开源 最好闭源吗

**Comment by tansar** [comment]
你就喜欢转移问题， 我问你提BUG你跟我扯别的。能不能正面问题

**Comment by donet5** [comment]
所以我说了你听不懂 ，你用我建的表要查就明白了

**Comment by tansar** [comment]
就你懂，还ORM始祖 脸都不要了。

**Comment by tansar** [comment]
比别人慢还威胁别人删博文  ，这你都做得出， 真是脸都不要了

**Comment by donet5** [comment]
做个人吧，恶意抹黑，说我不要脸

**Comment by tansar** [comment]
看看是谁在抹黑
![image](https://user-images.githubusercontent.com/12521832/175503247-fa021835-a305-4f92-b547-1a876b68d480.png)

**Comment by tansar** [comment]
这么拉挎还天天说吊打别人。

**Comment by donet5** [comment]
你拿 一个更新比较一试试就知道了  ，看清楚了是Update

**Comment by tansar** [comment]
呵呵，吊打 是你的专用词。

**Comment by tansar** [comment]
自己黑别人的时候就可以， 别人只是做了个测试，就说别人黑你。。。

**Comment by tansar** [comment]
本来做个测试就是可以相互提高 有问题解决问题，你这个态度问题

**Comment by tansar** [comment]
我也是用户， 难道我就不能做测试了？  谁规定我不能做测试？

**Comment by tansar** [comment]
后续我还会测 mysql postgresql

**Comment by tansar** [comment]
开源框架 还怕别人测。 真是涨见识了。

**Comment by donet5** [comment]
不好意思，你这种.NET CORE项目安装framework sqlsugar，所有ORM一起不分开进行测试，建表还是用的你的表建的，然后就去到处乱说别人垃圾 ，结果测试结果让用户打脸 ，还不反醒 ，我不怕被用户测，只怕小人

**Comment by tansar** [comment]
是的 开源就怕小人 如你 ，网络打手一帮人

**Comment by tansar** [comment]
我又说SQLSUGAR垃圾吗

**Comment by tansar** [comment]
我一直SQLSUGAR是比较好的框架 ， 是你自己觉得测试结果让你没面子 ， 就说我黑。

**Comment by tansar** [comment]
提了BUG 还不愿意改， 还不承认，悄悄的把ISSUES关闭， 我铁定你会悄悄的把这些BUG改了。

**Comment by donet5** [comment]
你把我发你的DEMO拿给别人跑跑，心里没点数吗？ 你自信的性能你认为没被打脸 吗？ 你哪怕把我的DEMO 多几个人测一下 就知道我说的是事实

**Comment by tansar** [comment]
嘴硬，坐等你悄悄改。

**Comment by tansar** [comment]
你发的DEMO好意思讲， 你怎么不把三个oRM放在一起运行 做个排名， 只跑你自己的是自嗨吗

**Comment by tansar** [comment]
重要的不是秒数， 重要的是排名 ，只是垫底而已， 这就是你说所谓吊打别人

**Comment by donet5** [comment]
不好意思我把HISQL一删就快了，为什么呢？

**Comment by donet5** [comment]
你连最基本正确测都做不到，还来谈测试了，你想让我最慢就最慢，你就不讲究事实？  谁的项目会装2个重量级ORM一起跑

**Comment by donet5** [comment]
![image](https://user-images.githubusercontent.com/12455385/175759403-4499e322-7d26-4b56-b010-9064452e03fc.png)
这个可以别人用我的DEMO跑的 ，也没见你快哪去

**Comment by donet5** [comment]
无非就是把 SqlSugar换成了.NET CORE版本的 DLL 和建表改用了 SqlSugar建表

**Comment by tansar** [comment]
![image](https://user-images.githubusercontent.com/12521832/175865625-767b70c7-4ef7-4c5b-97fa-0cbb882b84ea.png)

这是要笑死我呀， 自己建的一个表， 把主键去掉与我们有主键的对比，主要结果还比hisql慢。

**Comment by tansar** [comment]
![image](https://user-images.githubusercontent.com/12521832/175865739-0c22ea6e-57f0-41fb-b13d-ac22947e9129.png)

**Comment by tansar** [comment]
> 至于你说的PGSQL 我来和你科普一下 规范表： 表字表名小写和字段小写 这种是DBA最爱 ，优点 写SQL不需要 注意大小写 不需加 "" 非规范表： 字段用 ""包起来 ，写SQL必须大小写一样必须 ""
> 
> 2种模式是没办法共存的，要么用规范要么用非规范 ，SqlSugar支持2种模式 默认规范表


谢谢你的科普， 不过忘了告诉 你 hisql是解决了这个问题

**Comment by donet5** [comment]
![image](https://user-images.githubusercontent.com/12455385/176145557-98196a68-1c90-43f4-a5cf-0425094fb6e1.png)
加主双主键一样快
看你的源码通过 batchsize去调试来让你的代码变快，而这个batchsize是根据CPU不同效果是有差异的这也是你为什么测出来的结果这么搞笑，别人和你结果不一致，你只是针对你当前CPU 当前数据条数 列数 列的大小定制的， 换台电脑就不一样了

**Comment by donet5** [comment]
![image](https://user-images.githubusercontent.com/12455385/176146082-7fc90170-38a1-45b5-b4df-002ab7b0a3cc.png)

**Comment by donet5** [comment]
> 你们多学学[MongoDB.Driver](https://www.nuget.org/packages/MongoDB.Driver) 驱动的设计模式吧，freesql也好，sqlsugar也罢，EF什么的。什么hisql的 没一个好用的，特别是分库分表，差的狗屎，多学学MongoDB.Driver

好不好是用户决定的，有和无是另一个概念，MongoDB 是NO SQL ，当然你可以提出更好的例子

**Comment by znyet** [comment]
这样才是分库分表正确打开方式
https://www.nuget.org/packages/Dapper.Sharding

**Comment by donet5** [comment]
> 这样才是分库分表正确打开方式 https://www.nuget.org/packages/Dapper.Sharding
你可以说说这个表的优势吧 
第1: 没什么人用 ，NUGET总下载量就 2.7万 ，远达不到成熟的地步
第2: 底层代码就做了个TaskWhenll ，每个分表Sql请求一次
分表的间义于要精准的 插入哪个哪个表， 查询哪个表，实质是分表，
本质是只操作一个表，不是单纯的并发每个表跑一次吧

**Comment by znyet** [comment]
所以说你没去了解甚至使用过mongodb
也没用它去做过实际项目
GetDatabase
GetCollection
的精髓，还有自动列的思维

就只会看下载量，然后在那边沾沾自喜
tansar说你这人有问题是果然没错的
给你指mongodb驱动的设计思路
结果自己在那边无非就是想表达自己的框架很牛，很无敌的样子

**Comment by donet5** [comment]
> 所以说你没去了解甚至使用过mongodb 也没用它去做过实际项目 GetDatabase GetCollection 的精髓，还有自动列的思维
> 
> 就只会看下载量，然后在那边沾沾自喜 tansar说你这人有问题是果然没错的 给你指mongodb驱动的设计思路 结果自己在那边无非就是想表达自己的框架很牛，很无敌的样子


我更希望你是来解决问题，至于你说的这种获取库的方式 SqlSugar一样支持
````
var mysqldb = db.GetConnection("1");//获取config为1的数据库对象
var sqlServerdb = db.GetConnection("0");//获取默认对象
mysqldb.Queryable<Order>().ToList();
sqlServerdb.Queryable<Order>().ToList();
```

**Comment by donet5** [comment]
> 所以说你没去了解甚至使用过mongodb 也没用它去做过实际项目 GetDatabase GetCollection 的精髓，还有自动列的思维
> 
> 就只会看下载量，然后在那边沾沾自喜 tansar说你这人有问题是果然没错的 给你指mongodb驱动的设计思路 结果自己在那边无非就是想表达自己的框架很牛，很无敌的样子

你如果只是扔个东西，给我参考那就算了，我需要的把这个亮点说出来。而不是扔个XX框架我自个去看思路
