### ISSUE TITLE
Entity mapping error.Common Language Runtime detected an invalid program

### ISSUE THREAD

**Issue by mrreddevil2412** [donet5/SqlSugar#1040]
![image](https://user-images.githubusercontent.com/30259651/177031647-bc58d0fb-e3b0-46a7-adc7-a6d51978afdd.png)

**Comment by donet5** [comment]
1、getusernotupdate[i].staffcode 提到表达式外面看一下
2、如果有非数据库字段需要加上sugarcolums(isignore=true)

如果还有问题实体发出来看一下

**Comment by donet5** [comment]
Has the problem been solved？

**Comment by mrreddevil2412** [comment]
Thanks you!. I fixed. 
I change datatype from float to double 😅

**Comment by donet5** [comment]
What type of database do you have

What is the type of entity

What database

**Comment by mrreddevil2412** [comment]
> What type of database do you have
> 
> What is the type of entity
> 
> What database

Type of db float
Entity: float
Sqlserver

**Comment by donet5** [comment]
You this error I will deal with the following version, you use the correct first
![image](https://user-images.githubusercontent.com/12455385/177272347-97b9605a-36b2-43de-a2b4-3d9d2c62d0bb.png)

**Comment by mrreddevil2412** [comment]
> You this error I will deal with the following version, you use the correct first
> ![image](https://user-images.githubusercontent.com/12455385/177272347-97b9605a-36b2-43de-a2b4-3d9d2c62d0bb.png)
> 

Yes, i changed and fixed ^^
Thanks so munch

**Comment by donet5** [comment]
Float is also fine, and the transfer to C# may fail due to a data problem。
Standard Doblue is recommended
