### ISSUE TITLE
扩展ISugarQueryable接口使其参数支持Dictionary<string,object>或dynamic

### ISSUE THREAD

**Issue by cmp2080** [donet5/SqlSugar#1041]
扩展方法
ISugarQueryable<T> WhereClass(Dictionary<string,object> whereDict,bool ignoreDefaultValue=false)
或
ISugarQueryable<T> WhereClass(dynamic whereList, bool ignoreDefaultValue=false)

使用场景：
通信时，接收到 whereModels，可以在不提前声明ClassType的情况下，使用该接口

**Comment by donet5** [comment]
本地已实后面版本会发布

**Comment by donet5** [comment]
ISugarQueryable<T> WhereColumns(List<Dictionary<string, object>> columns, bool ignoreDefaultValue = false);
