### ISSUE TITLE
Sqlite 数据库 db.Insertable(insertObj).ExecuteCommand(); 和 db.Fastest<DC_Scene>().BulkCopy(lstData); 写入的datetime数据 格式不同

### ISSUE THREAD

**Issue by CyrusZhou-CN** [donet5/SqlSugar#1042]
![image](https://user-images.githubusercontent.com/4635861/177545498-35806ce0-904f-4440-893f-9a508a1b421d.png)

db.Insertable(insertObj).ExecuteCommand();
和
db.Fastest<DC_Scene>().BulkCopy(lstData);
写入的datetime数据 格式不同
![image](https://user-images.githubusercontent.com/4635861/177546138-eb7a687c-b64f-4e2a-b074-25482780a363.png)

**Comment by CyrusZhou-CN** [comment]
初级修复 https://github.com/CyrusZhou-CN/SqlSugar/commit/18090e4e7ffd53aeba5f3c73a90444481737741f

**Comment by donet5** [comment]
明天我看一下

**Comment by donet5** [comment]
GITHUB的代码已经更新，你可以测试一下

**Comment by donet5** [comment]
![image](https://user-images.githubusercontent.com/12455385/178100072-b9d61a95-a2e6-4b85-99b8-5af1d93f553c.png)
可以升级预览版本进行测试，有问题发新的 issue
