### ISSUE TITLE
关于多库事务的问题请教

### ISSUE THREAD

**Issue by xulei-Itachi** [donet5/SqlSugar#1044]
你好，Orm中对于跨库事务的大致伪代码如下，那么理论上，在"位置A"处是可能会产生异常，像这种场景，应该如何处理？
db1.beginTrans();
db2.beginTrans();
//business code 

db1.commitTrans();
//位置A
db2.commitTrans();

**Comment by donet5** [comment]
捕获  AggregateException  异常 添加补偿机质

**Comment by donet5** [comment]
市场上所有跨库基本上都是 失败重试+补偿 。如果有更好思路可以提供出来

**Comment by donet5** [comment]
还一种方案事务中方法启差异日志 https://www.donet5.com/Home/Doc?typeId=1204 
出错的话可以完整的拿到 更新 和更新后的数据

**Comment by donet5** [comment]
长期没有回复，先关闭有疑问发新的iusse
