### ISSUE TITLE
对于已经存在的历史数据，如何按日期分表（历史数据在一张表中，后续按月再分表），如何多次分表

### ISSUE THREAD

**Issue by itcsdnnet** [donet5/SqlSugar#1046]
对于已经存在的历史数据，如何按日期分表（历史数据在一张表中，后续按月再分表），如何多次分表?

修改表名到指定日期， 然面插入就会插入到新分表中了

_Originally posted by @donet5 in https://github.com/donet5/SqlSugar/issues/1045#issuecomment-1185094751_

历史表中比如存放了一年的数据，如果按照修改表名到指定日期的方式，是不是需要将所有数据拆分到不同的月表中。有没有可能，从分表开始起，历史数据存放一张表，后续的数据按月存放的方案。

**Comment by donet5** [comment]
目前老数据可以这么操作，分页每次50万查询到内存，然后bulkcopy插入分表

**Comment by donet5** [comment]
写个程序能够成功读取完 ，那么老数据就成功都扔进了分表

**Comment by itcsdnnet** [comment]
1. 停服，将历史数据拆分到分表中（数据量大或涉及表多不可取），启动服务
2. 历史数据事先插入到分表中，更新站点分表服务，删除历史表中分表数据
请问是否有更优方案，谢谢

**Comment by donet5** [comment]
目前只能这样，如果有老的代码还需调整一下

**Comment by itcsdnnet** [comment]
好的，感谢大佬
