### ISSUE TITLE
多租户能支持这三种模式吗，详细看内容

### ISSUE THREAD

**Issue by ghd258** [donet5/SqlSugar#1052]
方案一：按租户字段区分
此方案要求每个业务表包含 TenantId 字段，以便区分不同租户。假设当前租户值为 1：
查询时 自动附加条件 where TenantId = 1
插入时 自动赋值 TenantId = 1
更新时 自动附加条件 where TenantId = 1，防止修改其他租户的数据
删除时 自动附加条件 where TenantId = 1，防止删除其他租户的数据
方案二：按租户分表
此方案要求每个租户对应不同的数据表，如 Goods_1、Goods_2、Goods_3 分别对应 租户1、租户2、租户3 的商品表。
这其实就是一般的分表方案
方案三：按租户分库
场景1：同数据库实例（未跨服务器），租户间使用不同的数据库名或Schema区分，使用方法与方案二相同；
场景2：跨服务器分库

**Comment by donet5** [comment]
支持的

**Comment by donet5** [comment]
[https://www.donet5.com/Home/Doc?typeId=1205](https://gitee.com/link?target=https%3A%2F%2Fwww.donet5.com%2FHome%2FDoc%3FtypeId%3D1205)


[https://www.donet5.com/Home/Doc?typeId=2246](https://gitee.com/link?target=https%3A%2F%2Fwww.donet5.com%2FHome%2FDoc%3FtypeId%3D2246)

**Comment by donet5** [comment]
长时间不回复，先关闭，有疑问重新发issues

**Comment by ghd258** [comment]
方案一：按租户字段区分
此方案要求每个业务表包含 TenantId 字段，以便区分不同租户。假设当前租户值为 1：
查询时 自动附加条件 where TenantId = 1
插入时 自动赋值 TenantId = 1
更新时 自动附加条件 where TenantId = 1，防止修改其他租户的数据
删除时 自动附加条件 where TenantId = 1，防止删除其他租户的数据
方案二：按租户分表
此方案要求每个租户对应不同的数据表，如 Goods_1、Goods_2、Goods_3 分别对应 租户1、租户2、租户3 的商品表。
这其实就是一般的分表方案  

这两种好像不支持吧
https://www.cnblogs.com/FreeSql/p/16556303.html  这个写的比较明确 希望sqlsugar超越这个freesql

**Comment by donet5** [comment]
支持的 几行代码就搞定了

**Comment by donet5** [comment]
按租户字段区分 这个完全支持，并且支持表循环添加   ， 插入+更新有过滤器 自动添加租户ID , 删除文档有写也可以启用过滤器

**Comment by donet5** [comment]
方案二：按租户分表 
这个就更简单了

db.Queryable<T>().As(表名)
db.Insertable<T>().As(表名)
db.Updateable<T>().As(表名)
db.Deleteable<T>().As(表名)

**Comment by donet5** [comment]
当然你也可以用ORM自带的 自定义分表实现 方案二

**Comment by donet5** [comment]
SqlSugar 已经拥有重多成熟的项目使用
并且使用了SAAS相关的功能
https://www.donet5.com/Home/Doc?typeId=1215
