### ISSUE TITLE
[bug]JSON TO SQL  分页查询 总页数SQL问题

### ISSUE THREAD

**Issue by liaozb** [donet5/SqlSugar#1054]
![image](https://user-images.githubusercontent.com/12622501/184076887-245a65f0-6e13-4f01-b902-027c8349950c.png)
sqlserver count() 之后不能跟orderby

**Comment by donet5** [comment]
好的

**Comment by donet5** [comment]
源码已经修复，你可以测试一下，没问题我近期会发布到NUGET

**Comment by liaozb** [comment]
@donet5  Thanks♪(･ω･)ﾉ

**Comment by donet5** [comment]
[5.1.2-preview06](https://www.nuget.org/packages/SqlSugarCore/5.1.2-preview06)   版本已经发布，如果还有问题可以重开一个ISSUES
