### ISSUE TITLE
这个是不是应该不等于😉

### ISSUE THREAD

**Issue by liaozb** [donet5/SqlSugar#1055]
https://github.com/donet5/SqlSugar/blob/03e395b0da7ad02a22ff9229303f00bc4436e0fc/Src/Asp.NetCore2/SqlSugar/Json2Sql/Provider/Insertable/JsonInsertableProvider.cs#L26

**Comment by donet5** [comment]
好的这个我处理一下

**Comment by donet5** [comment]
源码已修复

**Comment by donet5** [comment]
NUGET 预计周一发布一个版本

**Comment by donet5** [comment]
已发布，如果还有问题，发布的ISSUE
