### ISSUE TITLE
SqlFunc.HasValue

### ISSUE THREAD

**Issue by skh1997** [donet5/SqlSugar#1056]
这个方法拼接成Sql条件变成这样了( CASE  WHEN ( [Email]<>'' AND [Email] IS NOT NULL ) ，拼接成一个错误的sql条件 THEN 1 ELSE 0 END )，原来是 ([Email]<>'' AND [Email] IS NOT NULL)，除非是在lambda中写SqlFunc.HasValue(x.Email) == true才拼接成正确的条件，很疑惑为啥必须这样写

**Comment by donet5** [comment]
你这个不是最新版本吧

**Comment by donet5** [comment]
![image](https://user-images.githubusercontent.com/12455385/184620822-b17729b5-7415-4ff6-8269-c58c95a6d19e.png)
我这边测试正常

**Comment by donet5** [comment]
提供完整测试用例

**Comment by skh1997** [comment]
![1660613578931](https://user-images.githubusercontent.com/46045819/184780047-ad1c434f-35d3-4586-b9a8-b170f4ff936f.jpg)
我用的版本是
![Snipaste_2022-08-16_09-35-46](https://user-images.githubusercontent.com/46045819/184780140-6bdc174d-ce15-4518-b34a-3391454598aa.png)

**Comment by skh1997** [comment]
![image](https://user-images.githubusercontent.com/46045819/184780268-8232eb1d-3743-4863-bbb2-0b27acb7f06a.png)
这样才会没有报错，sql语句正常

**Comment by skh1997** [comment]
@donet5

**Comment by donet5** [comment]
源码已经修复，可以进行测试，，NUGET下个版本会发布

**Comment by skh1997** [comment]
好的，多谢

**Comment by donet5** [comment]
5.1.2.2-preview01 已发布有问题，重新发ISSUES
