### ISSUE TITLE
扩展方法似乎不支持达梦

### ISSUE THREAD

**Issue by leehomlee** [donet5/SqlSugar#1060]
rt
![image](https://user-images.githubusercontent.com/11976286/186063939-8056613f-fc90-4949-ae42-494039820c7a.png)

**Comment by donet5** [comment]
扩展方法可以用，只是参数type没有值，这个我下面版本升级一下

**Comment by donet5** [comment]
源码已经修复

**Comment by donet5** [comment]
源码已添加，明天发布到NUGET预览版本
