### ISSUE TITLE
db.Insertable插入单条数据和列表数据时，DateTimeOffset的格式不同

### ISSUE THREAD

**Issue by luojianxhlxt** [donet5/SqlSugar#1062]
`//插入设备信息
var equipmentId1 = BaseFunc.GetNewId();
var equipmentId2 = BaseFunc.GetNewId();
db.Insertable(new List<Equipment>()
{
    new Equipment
    {
        CreateTime = DateTimeOffset.Now,
        CreatorId = PresetConstant.ROOT_ID,
        Id = equipmentId1,
        Name = "1号PLC",
        Port = 12345,
        Remark = "测试数据",
        ServerIp = "127.0.0.1",
        Type = EquipmentTypeEnum.PLC
    },
    new Equipment
    {
        CreateTime = DateTimeOffset.Now,
        CreatorId = PresetConstant.ROOT_ID,
        Id = equipmentId2,
        Name = "2号PLC",
        Port = 12445,
        Remark = "测试数据",
        ServerIp = "127.0.0.1",
        Type = EquipmentTypeEnum.PLC
    },
}).ExecuteCommand();
//插入上位机信息
var upperComputerId = BaseFunc.GetNewId();
db.Insertable(new UpperComputer
{
    CreateTime = DateTimeOffset.Now,
    CreatorId = PresetConstant.ROOT_ID,
    Id = upperComputerId,
    Ip = "127.0.0.1",
    Name = "实例上位机",
    Place = "实例位置",
    Remark = "上位机备注"
}).ExecuteCommand();`

![PLC](https://user-images.githubusercontent.com/8614534/186890959-502e4fbc-9ea1-4533-8e61-982d279dee58.png)
![上位机](https://user-images.githubusercontent.com/8614534/186890983-3b9a63db-9baa-4914-b3d1-b0e0dfb617d9.png)

**Comment by donet5** [comment]
是SQLITE吗 ，建表语句发一下

**Comment by luojianxhlxt** [comment]
是SQLite
`public abstract class KeyEntity
{
    /// <summary>
    /// Id
    /// </summary>
    [SugarColumn(IsIdentity = false, IsPrimaryKey = true, ColumnDescription = "Id")]
    public long Id { get; set; }
    /// <summary>
    /// 是否删除
    /// </summary>
    [SugarColumn(ColumnDescription = "是否删除", IsNullable = false)]
    public bool IsDeleted { get; set; } = false;
    /// <summary>
    /// 创建者Id
    /// </summary>
    [SugarColumn(ColumnDescription = "创建者Id", IsNullable = false)]
    public long CreatorId { get; set; }
    /// <summary>
    /// 创建时间
    /// </summary>
    [SugarColumn(ColumnDescription = "创建时间", IsNullable = false)]
    public DateTimeOffset CreateTime { get; set; }
    /// <summary>
    /// 修改者Id
    /// </summary>
    [SugarColumn(ColumnDescription = "修改者Id", IsNullable = true)]
    public long? ModifierId { get; set; }
    /// <summary>
    /// 修改时间
    /// </summary>
    [SugarColumn(ColumnDescription = "修改时间", IsNullable = true)]
    public DateTimeOffset? ModifyTime { get; set; }
    /// <summary>
    /// 删除者Id
    /// </summary>
    [SugarColumn(ColumnDescription = "删除者Id", IsNullable = true)]
    public long? DeleterId { get; set; }
    /// <summary>
    /// 删除时间
    /// </summary>
    [SugarColumn(ColumnDescription = "删除时间", IsNullable = true)]
    public DateTimeOffset? DeleteTime { get; set; }
}`

`public abstract class NameEntity : KeyEntity
{
    /// <summary>
    /// 名称
    /// </summary>
    [SugarColumn(ColumnDescription = "名称", IsNullable = false, UniqueGroupNameList = new[] { "Name" }, Length = 50)]
    public string Name { get; set; } = string.Empty;
    /// <summary>
    /// 备注
    /// </summary>
    [SugarColumn(ColumnDescription = "备注", IsNullable = true, Length = 200)]
    public string? Remark { get; set; }
}`

Equipment和UpperComputer均继承自NameEntity

**Comment by donet5** [comment]
源码已经更新，可以测试一下，晚点我会发布个预览版本到nuget

**Comment by donet5** [comment]
NUGET  已发布预览版本 5.1.2.4-preview06

**Comment by donet5** [comment]
如果还有问题发新的ISSUES
