### ISSUE TITLE
关于sqlsugar在pgsql下进行or查询报错

### ISSUE THREAD

**Issue by endysaiwang** [donet5/SqlSugar#1063]
pgsql   xxx="xxxx" or xxx="xxxxxxx"  ，该场景下转化的sql 是  WHERE (("id" ='80d7396f-983a-4c92-b9a3-2ab350c63025') | ("name"='801号') ) ，该sql 应该为    WHERE (("id" ='80d7396f-983a-4c92-b9a3-2ab350c63025') OR ("name"
![sqlsugar-bug](https://user-images.githubusercontent.com/4568933/187585759-735db8cb-185e-4bea-a026-b9ec527c911c.png)
='801号') )

**Comment by donet5** [comment]
拼接表达式把And换成AndAlso

**Comment by donet5** [comment]
Or换成 OrElse
