### ISSUE TITLE
报错信息的描述不准确

### ISSUE THREAD

**Issue by vcup** [donet5/SqlSugar#1069]
https://github.com/donet5/SqlSugar/blob/8605b02715b58aa18d838ccb6c5ca1a7dc88c8b7/Src/Asp.Net/SqlSugar/Realization/Sqlite/DbMaintenance/SqliteDbMaintenance.cs#L370

这里明明判断的是等于integer的情况是异常，却报告说identity只能是Integer类型？

**Comment by donet5** [comment]
这块后面优化 ，你实是自增就用int 不需要指定什么类型  isidentity=true,

**Comment by donet5** [comment]
源码已经优化，后面NUGET新版本同步

**Comment by donet5** [comment]
![image](https://user-images.githubusercontent.com/12455385/188359915-8aaa6603-ad56-4ea4-9a69-90d65a131b27.png)

**Comment by vcup** [comment]
> 这块后面优化 ，你实体是自增就用int 不需要指定什么类型 ，加上 isprmarykey=true,isidentity=true,

了解，实际上我也是这样解决的
