### ISSUE TITLE
db.Updateable(updateObj).ReSetValue的DateTimeOffset格式不符合预期

### ISSUE THREAD

**Issue by luojianxhlxt** [donet5/SqlSugar#1071]
SQLite
`public abstract class KeyEntity { /// <summary> /// Id /// </summary> [SugarColumn(IsIdentity = false, IsPrimaryKey = true, ColumnDescription = "Id")] public long Id { get; set; } /// <summary> /// 是否删除 /// </summary> [SugarColumn(ColumnDescription = "是否删除", IsNullable = false)] public bool IsDeleted { get; set; } = false; /// <summary> /// 创建者Id /// </summary> [SugarColumn(ColumnDescription = "创建者Id", IsNullable = false)] public long CreatorId { get; set; } /// <summary> /// 创建时间 /// </summary> [SugarColumn(ColumnDescription = "创建时间", IsNullable = false)] public DateTimeOffset CreateTime { get; set; } /// <summary> /// 修改者Id /// </summary> [SugarColumn(ColumnDescription = "修改者Id", IsNullable = true)] public long? ModifierId { get; set; } /// <summary> /// 修改时间 /// </summary> [SugarColumn(ColumnDescription = "修改时间", IsNullable = true)] public DateTimeOffset? ModifyTime { get; set; } /// <summary> /// 删除者Id /// </summary> [SugarColumn(ColumnDescription = "删除者Id", IsNullable = true)] public long? DeleterId { get; set; } /// <summary> /// 删除时间 /// </summary> [SugarColumn(ColumnDescription = "删除时间", IsNullable = true)] public DateTimeOffset? DeleteTime { get; set; } }`

`public abstract class NameEntity : KeyEntity { /// <summary> /// 名称 /// </summary> [SugarColumn(ColumnDescription = "名称", IsNullable = false, UniqueGroupNameList = new[] { "Name" }, Length = 50)] public string Name { get; set; } = string.Empty; /// <summary> /// 备注 /// </summary> [SugarColumn(ColumnDescription = "备注", IsNullable = true, Length = 200)] public string? Remark { get; set; } }`

`public class PLCSignalInteraction : NameEntity
{
    /// <summary>
    /// 序号
    /// </summary>
    [SugarColumn(ColumnDescription = "序号", IsNullable = false)]
    public int Order { get; set; }
}`

`/// <summary>
    /// 更新批量实体
    /// </summary>
    /// <param name="entities"></param>
    /// <returns></returns>
    public virtual async Task<bool> UpdateAsync(List<TEntity> entities)
    {
        var currentUserId = _baseService.GetCurrentUserId();
        return await _sqlSugarScopeProvider.Updateable<TEntity>(entities)
            .IgnoreColumns(a => new
            {
                a.CreateTime,
                a.CreatorId
            })
            .ReSetValue(a =>
            {
                a.ModifierId = currentUserId;
                a.ModifyTime = DateTimeOffset.Now;
            })
            .ExecuteCommandHasChangeAsync();
    }`

结果ModifyTime字段在查询时报错，
2022/9/6 上午 11:08:21 +08:00 is not a valid value for DateTimeOffset.
![企业微信截图_20220906141041](https://user-images.githubusercontent.com/8614534/188559524-d82ae9a0-be18-4469-8072-41f73d531a70.png)

**Comment by donet5** [comment]
好的

**Comment by donet5** [comment]
[5.1.2.7-preview02](https://www.nuget.org/packages/SqlSugarCore/5.1.2.7-preview02) 

发布了一个预览版本
