### ISSUE TITLE
Sql Server 意大利语float用逗号代表小数点，更新操作时报错

### ISSUE THREAD

**Issue by csm12s** [donet5/SqlSugar#1072]
[ERR] Error converting data type nvarchar to float., UPDATE S SET S.[NstRef]=T.[NstRef],

。。。

SELECT 
...,
N'284,484' AS [SWeight],

**Comment by csm12s** [comment]
数值是284.484

**Comment by donet5** [comment]
你实体是什么类型

**Comment by csm12s** [comment]
数据库是float，net实体是double?, 数据库中执行select语句出来的数字是这样子的：284,484

我添加了下列代码后报错没有了

...\SqlSugar\Abstract\SqlBuilderProvider\UpdateBuilder.cs

在这个方法里添加如下public virtual object FormatValue(object value)：

else if (type == UtilConstants.DobType
                    || type == UtilConstants.FloatType
                    || type == UtilConstants.DecType)
                {
                    return value;
                }

**Comment by csm12s** [comment]
![image](https://user-images.githubusercontent.com/64699457/189047986-33e5dd5e-90df-4da4-8acd-922e628a83a9.png)

**Comment by csm12s** [comment]
![image](https://user-images.githubusercontent.com/64699457/189048083-dea1e777-76d6-4257-9e76-f217e1b3e8b9.png)

**Comment by csm12s** [comment]
请问public virtual object FormatValue(object value)里面为什么要把数字转换为字符串处理呢

**Comment by donet5** [comment]
源码更新了，你可以用源码测试一下，后面会同步到NUGET

**Comment by donet5** [comment]
SqlSugarCore 5.1.2.8-preview02  已经发布预览版本，如果还有问题重新发ISSUES
