### ISSUE TITLE
意大利语逗号

### ISSUE THREAD

**Issue by csm12s** [donet5/SqlSugar#1074]
![image](https://user-images.githubusercontent.com/64699457/189840050-d92fec8b-1a88-4218-9656-4d0425daddf2.png)

。。。 ,  62416,108585 AS [RapidLength],  58,028492 AS [RapidTime], 
 84511,570706 AS [CutLength]。。。

真实数据：
, 62416.108585 AS [RapidLength],58.028492 AS [RapidTime],84511.570706 AS [CutLength]

是不是要做这种修改：

else if (UtilMethods.IsNumber(type.Name)) 
                {
					//return value;
					return "'" + value + "'";
				}

![image](https://user-images.githubusercontent.com/64699457/189840740-172ebb7c-c158-4aea-b13f-065202c489f2.png)

**Comment by donet5** [comment]
我已经按你上次方法改了，我这边没环境重现不了，你到底要改成什么样子

**Comment by donet5** [comment]
什么样子是Ok的

**Comment by donet5** [comment]
已经按你需求改了，还有问题 提供你测试过的代码。

**Comment by csm12s** [comment]
...\SqlSugar\Abstract\SqlBuilderProvider\UpdateBuilder.cs

在这个方法里添加如下public virtual object FormatValue(object value)：

else if (UtilMethods.IsNumber(type.Name)) 
                {
                    // Italian
                    return value.ToString().Replace(",", ".");
				}

**Comment by csm12s** [comment]
测试没问题

**Comment by csm12s** [comment]
这个改动在客户那里测试没问题了
请问这个更新到dll里面了吗
