### ISSUE TITLE
是否SqlSugar出现Bug问题？

### ISSUE THREAD

**Issue by juMa-o** [donet5/SqlSugar#1076]
我创建了一个接口类，其中写了一个 SqlSugarScope  和 SqlSugarScopeProvider  类型的属性，保存主库和从库的信息。
实现了单例注入，并且让其 SqlSugarClient 监控 sql的执行。但是日志监控在类库中使用并不生效。只有在控制器中使用才会生效。
请问是不是Bug？
![image](https://user-images.githubusercontent.com/86597228/190088353-a91ccf12-fb23-481f-892b-799efc21b419.png)
![image](https://user-images.githubusercontent.com/86597228/190088399-c5cf090e-6771-4f19-a44d-b6e6556d87ea.png)

**Comment by juMa-o** [comment]
执行后，日志监控不生效
![image](https://user-images.githubusercontent.com/86597228/190090517-304e9318-8ccf-41fc-9754-327ce5643daf.png)

**Comment by donet5** [comment]
SqlSugarScope入门看一下，有介绍如何打印SQL

**Comment by donet5** [comment]
SqlSugarClient和SqlSugarScope 用法是有区别的

**Comment by juMa-o** [comment]
好的，感谢
