### ISSUE TITLE
How to Join Tables from Different Databases in SQL Server

### ISSUE THREAD

**Issue by mrreddevil2412** [donet5/SqlSugar#1078]
Model: ModJobsEntity in DBConnection
Model: HRDynamicCategoryEntity in DBConnectionHR (link server)

![image](https://user-images.githubusercontent.com/30259651/191155850-ab01413e-b5a5-42b8-b447-2a2e9ce5e79c.png)

**Comment by SimTsai** [comment]
u can try use sql server linkserver link db2 to db1.
and set HRxxxEntity tableName as full link name

**Comment by mrreddevil2412** [comment]
> u can try use sql server linkserver link db2 to db1. and set HRxxxEntity tableName as full link name

![image](https://user-images.githubusercontent.com/30259651/191156774-86e65629-607e-4a7b-bd93-718de51f6e82.png)
Is it like this?

**Comment by SimTsai** [comment]
perhaps, you can try it yourself, i donot have env to test that. 
debug print sqlvalue or aop to print generate sql.

**Comment by donet5** [comment]
```
//多表跨库
var list1 = db.Queryable<Order>().AS("xx.dbo.order") // AS("")
        .LeftJoin<OrderItem>((o,i)=> o.Id == i.OrderId).AS<OrderItem>("yy.dbo.OrderItem") //AS<T>
        .LeftJoin<Custom>((o, i, c) => c.Id == o.CustomId) .AS<Custom>("zz.dbo.Custom")//AS<T>
        .Select((o,i,c)=>new classA() { oid=o.Id , iname=i.Name })
        .ToList();
```

**Comment by donet5** [comment]
The function you said will be developed, at present, can only be implemented in the way I mentioned above

**Comment by donet5** [comment]
The function you said will be developed, at present, can only be implemented in the way I mentioned above

**Comment by mrreddevil2412** [comment]
> ```
> //多表跨库
> var list1 = db.Queryable<Order>().AS("xx.dbo.order") // AS("")
>         .LeftJoin<OrderItem>((o,i)=> o.Id == i.OrderId).AS<OrderItem>("yy.dbo.OrderItem") //AS<T>
>         .LeftJoin<Custom>((o, i, c) => c.Id == o.CustomId) .AS<Custom>("zz.dbo.Custom")//AS<T>
>         .Select((o,i,c)=>new classA() { oid=o.Id , iname=i.Name })
>         .ToList();
> ```
Great ^^

> perhaps, you can try it yourself, i donot have env to test that. debug print sqlvalue or aop to print generate sql.


Yes, Thanks u ^^
Is running 🥉
