### ISSUE TITLE
关于查询条件字符集的问题

### ISSUE THREAD

**Issue by xulei-Itachi** [donet5/SqlSugar#1090]
现有一DB, 
 where xxx in ('中文1', '中文1')
查不出数据，
要写成  where xxx in (N'中文1',N '中文1')
请问orm中怎么写

**Comment by donet5** [comment]
it.Contains(it.name,true)  新版本支持

**Comment by donet5** [comment]
还有疑问吗？

**Comment by xulei-Itachi** [comment]
无

**Comment by donet5** [comment]
names.Contains(p.name,false) 应该是false说错了

**Comment by heaxo** [comment]
@DotNetNext 你好，请问value = N'值'，如何写
