### ISSUE TITLE
关于监控SQL执行时间的问题

### ISSUE THREAD

**Issue by xulei-Itachi** [donet5/SqlSugar#1096]
我按照文档上所写，使用 db.Ado.SqlExecutionTime.TotalSeconds 获取sql执行时间，但是获取到的时间是负的是什么情况？
比如 ： -63803510270.28474 ， -0.0026422这样的值。
AOP添加方式是：db =>
            {
                //单例参数配置，所有上下文生效
                db.Aop.OnLogExecuting = (sql, pars) =>
                {
                    //Console.WriteLine(sql);//输出sql
                    //执行时间超过1秒
                    if (db.Ado.SqlExecutionTime.TotalSeconds > 1)
                    {
                        //代码CS文件名
                        var fileName = db.Ado.SqlStackTrace.FirstFileName;
                        //代码行数
                        var fileLine = db.Ado.SqlStackTrace.FirstLine;
                        //方法名
                        var FirstMethodName = db.Ado.SqlStackTrace.FirstMethodName;
                        //db.Ado.SqlStackTrace.MyStackTraceList[1].xxx 获取上层方法的信息

                    }
                };
            }

**Comment by donet5** [comment]
db.Aop.OnLogExecuting = (sql, pars) =>  事件错了，这个执行前事件

**Comment by xulei-Itachi** [comment]
懂了，我的锅，眼神不太好使。
