### ISSUE TITLE
MySql连接异常

### ISSUE THREAD

**Issue by sunyu005** [donet5/SqlSugar#1101]
SqlSugar版本：5.0.4.7
MySql版本：8.0.31
连接异常：
![cap_8331404509763](https://user-images.githubusercontent.com/48470418/202160725-f60ad9ed-1728-4f40-82b7-5ca228dc6206.png)

SqlSugar.SqlSugarException
  HResult=0x80131500
  Message=中文提示 :  连接数据库过程中发生错误，检查服务器是否正常连接字符串是否正确，实在找不到原因请先Google错误信息：Unable to connect to any of the specified MySQL hosts..
English Message : Connection open error . Unable to connect to any of the specified MySQL hosts.
  Source=SqlSugar
  スタック トレース:
   場所 SqlSugar.AdoProvider.GetDataReader(String sql, SugarParameter[] parameters)
   場所 SqlSugar.AdoProvider.SqlQuery[T,T2,T3,T4,T5,T6,T7](String sql, Object parameters)
   場所 SqlSugar.AdoProvider.SqlQuery[T](String sql, SugarParameter[] parameters)
   場所 SqlSugar.AdoProvider.SqlQuery[T](String sql, Object parameters)
   場所 SqlSugar.DbMaintenanceProvider.<>c__DisplayClass44_0`1.<GetListOrCache>b__0()
   場所 SqlSugar.ReflectionInoCore`1.GetOrCreate(String cacheKey, Func`1 create)
   場所 SqlSugar.ReflectionInoCacheService.GetOrCreate[V](String cacheKey, Func`1 create, Int32 cacheDurationInSeconds)
   場所 SqlSugar.DbMaintenanceProvider.GetListOrCache[T](String cacheKey, String sql)
   場所 SqlSugar.DbMaintenanceProvider.GetTableInfoList(Boolean isCache)
   場所 SqlSugar.DbMaintenanceProvider.IsAnyTable(String tableName, Boolean isCache)
   場所 Tellus.Core.Module.TellusCoreModule.BuildModule(IServiceProvider provider)
   場所 Tellus.Core.Module.AppModule.BuildModule(IApplicationBuilder app)
   場所 Microsoft.AspNetCore.Builder.ApplicationBuilderExtensions.<>c__DisplayClass0_0.<BuildApplication>b__1(AppModule module)
   場所 System.Collections.Generic.List`1.ForEach(Action`1 action)
   場所 Microsoft.AspNetCore.Builder.ApplicationBuilderExtensions.BuildApplication(IApplicationBuilder app, IHostEnvironment env, IHostApplicationLifetime applicationLifetime)
   場所 AssetManager.Api.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IHostApplicationLifetime applicationLifetime) (D:\GitLab\AssetManageAPI\AssetManagerSystem\src\AssetManager.Api\Startup.cs):行 55
   場所 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   場所 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   場所 Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   場所 Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   場所 Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   場所 Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   場所 Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   場所 Microsoft.WebTools.BrowserLink.Net.HostingStartup.<>c__DisplayClass1_0.<Configure>b__0(IApplicationBuilder app)
   場所 Microsoft.AspNetCore.Watch.BrowserRefresh.HostingStartup.<>c__DisplayClass1_0.<Configure>b__0(IApplicationBuilder app)
   場所 Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__31.MoveNext()

**Comment by donet5** [comment]
```
new MySqlConnection(db.CurrentConnectionConfig.ConnectionString).Open();
```
用原生进行测试 看能不能连上去

**Comment by donet5** [comment]
还有疑问吗

**Comment by donet5** [comment]
长时间未回复，先关闭，有问题重新发问
