### ISSUE TITLE
如何增加一种新数据库的支持？

### ISSUE THREAD

**Issue by hua0129** [donet5/SqlSugar#1103]
目前代码中的数据库，诸如mysql，oracle等都是和SqlSugar在一起打包。
我们需要增加一种新数据库，也需要这样做吗？

有没有方法，独立增加一个包，只包含单个数据库的独立适配？

**Comment by donet5** [comment]
可以看扩展数据库，目前很clickhouse  access等都是外部扩展的

**Comment by donet5** [comment]
https://www.donet5.com/Home/Doc?typeId=2411

**Comment by hua0129** [comment]
多谢。 扩展数据库的方式，功能有没有局限？ 可以独立打包吗？

**Comment by donet5** [comment]
可以，你可以看customtest 这个用例
