### ISSUE TITLE
达梦默认驱动sqlsugarcore.dm的驱动会将数据库字段为varchar(36)转guid

### ISSUE THREAD

**Issue by HugoChanD** [donet5/SqlSugar#1104]
用sqlsugarcore.dm的驱动会将数据库字段为varchar(36)自动转为guid导致报错  换了官方的驱动没有这个问题https://www.donet5.com/Ask/9/16481 这个问题类似
![image](https://user-images.githubusercontent.com/19699493/203233215-78fed7e5-475b-46e4-ad0e-a2342c92e732.png)

![image](https://user-images.githubusercontent.com/19699493/203233263-caf69545-b58d-4f6c-9267-836464de2075.png)
![image](https://user-images.githubusercontent.com/19699493/203233303-98e685a4-4a9c-425a-bf9c-f6f0d69557d9.png)

**Comment by donet5** [comment]
sqlsugarcore.dm 就是官方驱动，版本低些 这个问题不大，换个长度吧

**Comment by donet5** [comment]
升级影响比较大

**Comment by donet5** [comment]
或者你把这个dll发我邮箱 ， 610262374@qq.com 我更新到nuget 你手动更新 sqlsugarcore.dm

**Comment by HugoChanD** [comment]
恩 目前的方式就是改长度 顺便把官方驱动发你邮箱了
