### ISSUE TITLE
CodeFirst兼容EF，没有ColumnDataType字段、如何设置Unicode string?

### ISSUE THREAD

**Issue by Tinyipfaan** [donet5/SqlSugar#1107]
<img width="844" alt="企业微信截图_1669603397621" src="https://user-images.githubusercontent.com/119273671/204181821-b6eb1fb2-4969-452d-82f7-6f9b3ee17865.png">
<img width="711" alt="企业微信截图_16696034651796" src="https://user-images.githubusercontent.com/119273671/204181879-5b22e956-9686-4ad6-8978-0155edb97048.png">

**Comment by donet5** [comment]
![image](https://user-images.githubusercontent.com/12455385/204191256-e0fb6e5d-8cba-4f55-82b0-394ae67987a6.png)

**Comment by donet5** [comment]
你应该设置回调函数时面的 属性

**Comment by Tinyipfaan** [comment]
> 你应该设置回调函数时面的 属性

这里只是名字不一样，实际是一样的
<img width="635" alt="企业微信截图_16696084447664" src="https://user-images.githubusercontent.com/119273671/204192146-f1ac6f56-4194-4dd2-8295-4bc2eeb5cfe8.png">

**Comment by donet5** [comment]
DataType   是这个名字

**Comment by donet5** [comment]
还有疑问吗

**Comment by donet5** [comment]
还有疑问重新发isssue
