### ISSUE TITLE
Code First 兼容多库，如何设置Unicode String

### ISSUE THREAD

**Issue by csm12s** [donet5/SqlSugar#1108]
如果要统一设置Nvarchar，是不是只能这样根据具体数据库来指定
如果不指定默认生成varchar，有没有什么设置改成nvarchar
EF Core 默认string会映射为nvarchar

![image](https://user-images.githubusercontent.com/64699457/205473050-54041736-e9ea-4ab8-b3a9-67d3f0417fda.png)

**Comment by donet5** [comment]
Data="  varchar(xx) xxxx  "    差不多可以这样

**Comment by donet5** [comment]
![image](https://user-images.githubusercontent.com/12455385/205474873-ca72d40e-eedf-4b89-89b4-213750f0878c.png)
AOP可以会局设置

**Comment by csm12s** [comment]
建议 默认string 映射为nvarchar

**Comment by csm12s** [comment]
我想知道 不用DataType  怎么设置 Unicode

DataType 不兼容多库

**Comment by donet5** [comment]
AOP里面的DataType可以支持多库，因为逻辑可以控制

**Comment by donet5** [comment]
![SIDG`PB6 B7YL$SQ{RMY)0L](https://user-images.githubusercontent.com/12455385/206412113-438fa3ad-6e9c-491e-a105-8f0e0b69dff3.png)
支持了新功能直接 设置SqlServer为Nvarchar

**Comment by donet5** [comment]
升级到预览版本 SqlSugarCore 5.1.3.39-preview03
