### ISSUE TITLE
it.ID.SelectAll() 获取日期出错

### ISSUE THREAD

**Issue by Tinyipfaan** [donet5/SqlSugar#1110]
<img width="373" alt="企业微信截图_16702323329208" src="https://user-images.githubusercontent.com/119273671/206140284-ccf7efd2-8441-48b1-8212-3dd452bd00b5.png">

![企业微信截图_16704052852907](https://user-images.githubusercontent.com/119273671/206140963-dca4cc63-fdf4-448d-b3fc-bb0e6a429dc4.png)

数据库中日期字段默认值1900-01-01 00:00:00.000 Dto里面映射成了0001...

public DateTime UserDate { get; set; }

如果dto继承model，好像会映射正确

数据库是SQLServer

**Comment by donet5** [comment]
这个需要提供完整DEMO ，否则我这边不能够重现  ,https://www.donet5.com/Home/Doc?typeId=2366 这个提问模版

**Comment by donet5** [comment]
![image](https://user-images.githubusercontent.com/12455385/206143995-8637e1ee-78cf-4830-8c47-63476824e595.png)
