### ISSUE TITLE
.SelectAll()获取日期出错

### ISSUE THREAD

**Issue by Tinyipfaan** [donet5/SqlSugar#1113]
```
var listDto = await GetSugarContext().Queryable
            <LantekPart, LantekMaterial>
            ((it, material)
            => new JoinQueryInfos(
                JoinType.Left, it.DisMatRef == material.MatRef
            ))
            .Where(it => prdRefs.Contains(it.PrdRef))
            .Select((it, material)
                => new LantekPartDto
                {
                    // part.all
                    RecID = it.RecID.SelectAll(),
                    ImageBmp = it.Image,

                    // material
                    Density = material.Density,
                })
            .ToListAsync();
```
<img width="401" alt="企业微信截图_16708215718180" src="https://user-images.githubusercontent.com/119273671/206965980-330e199b-5044-41df-a3d2-b20764f27a40.png">
<img width="420" alt="企业微信截图_16708216825009" src="https://user-images.githubusercontent.com/119273671/206966042-2af50646-f736-4dbe-81b0-58666337ab2f.png">

Dto字段density拿到了，entity字段有的没拿到

<img width="268" alt="企业微信截图_16708217378429" src="https://user-images.githubusercontent.com/119273671/206966081-1e69663c-b82c-4477-8659-e1c61a03b520.png">
数据库中记录分别是一个时间和空string

LantekPart, LantekMaterial两个表都有RecID
```
public DateTime DisPriceDate { get; set; }
public string DisProfileRef { get; set; }
```
```
[Column("DIS_PriceDate")]
    [Comment("Last price modification")]
    public DateTime DisPriceDate { get; set; }

[Column("DIS_ProfileRef")]
    [Comment("Profile")]
    public string DisProfileRef { get; set; }
```

这种就取到了
<img width="409" alt="企业微信截图_1670822023437" src="https://user-images.githubusercontent.com/119273671/206966279-fd4d6666-a0ac-4ffa-8950-7769bc1311f8.png">

你底层可能做值的判断了，entity的字段在数据库中都是非Null，这个改不了。

**Comment by donet5** [comment]
提供完整加测试数据用例   https://www.donet5.com/Home/Doc?typeId=2366 按这个模版提供

**Comment by donet5** [comment]
DTO如果字段名字不一样是查询不到的，要一模一样

**Comment by donet5** [comment]
我看你的表名都有下划线

**Comment by donet5** [comment]
```cs
//自动返回DTO : 请升级 5.1.3.35  
var listDto= db.Queryable<Student>()
            .Select(it=>new StudentDto()
             {
                  Count=100 //手动指定一列在自动映射
             },
             true)//true表式开启自动映射
            .ToList();//返回List
```
可以试试自动映射功能 ，这个是以实体名字映射的

**Comment by donet5** [comment]
SelectAll目前如果DTO不加特性和数据库不一样是没办法映射的

**Comment by Tinyipfaan** [comment]
建议自动映射的时候按照C#字段映射，否则添加说明

**Comment by Tinyipfaan** [comment]
可以映射了，加特性是指什么，为什么我Dto继承Entity这个就能映射成功了

**Comment by donet5** [comment]
继承带有实体类特性
