### ISSUE TITLE
提问或建议 针对DateTime的默认值

### ISSUE THREAD

**Issue by Sheldon-NULL** [donet5/SqlSugar#1114]
## 当前是否已经实现对像CreateTime或UpdateTime这种字段，插入或更新能赋予当前时间的值呢？

我的想法如果能做到这种简单写完就能实现就很快
```  
[SugarClumn(IsOnlyIgnoreInsert =true,DefaultVaule   = DateTime.Now.ToString())]
public DateTime? CreateTime { get; set; } 
``` 

希望能得到解决方案，或者能添加这个功能。

**Comment by donet5** [comment]
![image](https://user-images.githubusercontent.com/12455385/208588232-57a1087d-ec24-4eb7-8140-835936dcdd71.png)
这个功能目前只支持了插入，我这2天把更新也支持一下

**Comment by Sheldon-NULL** [comment]
非常感谢大佬

**Comment by Sheldon-NULL** [comment]
留着给您更新完，再关闭吧

**Comment by donet5** [comment]
![image](https://user-images.githubusercontent.com/12455385/208639657-51ce119a-5130-4fb4-bc21-d0877606a9ff.png)

**Comment by donet5** [comment]
最新预览本已支持了，更新可以试用了

**Comment by Sheldon-NULL** [comment]
SqlSugarCoreNoDrive这个包应该没上传更新吧

**Comment by donet5** [comment]
没有，我现在上传

**Comment by donet5** [comment]
已发布 勾一下预览

**Comment by Sheldon-NULL** [comment]
ok,已经用起来了。
然后一个小建议：我觉得这个属性还有优化空间，可以再考虑把DateTime.ToString(),这个有关控制时间格式的重载做进去，甚至像DateTime.Now.AddDays(),这种时间运算也不是不可以考虑的。

**Comment by donet5** [comment]
这个也计划中，属性自定义方式

**Comment by donet5** [comment]
查询 插入 更新 有套自定义体系，后面还要支持值对象

**Comment by donet5** [comment]
这个先关闭有新问题在发新ISSUE
