### ISSUE TITLE
表达式BUG

### ISSUE THREAD

**Issue by donet5** [donet5/SqlSugar#835]
https://www.donet5.com/Ask  统一提交入口

**Comment by skh1997** [comment]
![image](https://user-images.githubusercontent.com/46045819/190570430-da312614-4413-4d97-8fb6-64df7cac5151.png)
SqlFunc.IIF语法错误，sqlsugar版本5.1.3.1

**Comment by donet5** [comment]
> ![image](https://user-images.githubusercontent.com/46045819/190570430-da312614-4413-4d97-8fb6-64df7cac5151.png) SqlFunc.IIF语法错误，sqlsugar版本5.1.3.1
 SqlFunc.IIF(it.IsDeleted==true,"a","b"

**Comment by donet5** [comment]
it.IsDeleted?  "a" : "b"  这样也行  sqlfunc.iif 后面处理一下

**Comment by donet5** [comment]
源码已修复，后续一些时间会在NUGET发布
