### ISSUE TITLE
DM 数据库 bug

### ISSUE THREAD

**Issue by wbz-hot** [donet5/SqlSugar#860]
![image](https://user-images.githubusercontent.com/27388711/103146073-23161300-477f-11eb-96b4-17f151e15b48.png)

1.DmDbMaintenance 下 这个linq是有可能获取null值的，错误：序列不包含任何匹配元素 
2.缺少数据类型
 SqlSugar.DmDbBind.MappingTypesConst.Add(new KeyValuePair<string, SqlSugar.CSharpDataType>("double precision", SqlSugar.CSharpDataType.@double));
            SqlSugar.DmDbBind.MappingTypesConst.Add(new KeyValuePair<string, SqlSugar.CSharpDataType>("binary", SqlSugar.CSharpDataType.@long));

**Comment by donet5** [comment]
binary 到底是long类型还是 byte[]

**Comment by donet5** [comment]
如果是long number(19,0) 就可以了

**Comment by donet5** [comment]
binary我改成byte[]你看看有没有问题 ，dm 达梦的 blob就是byte[]

**Comment by donet5** [comment]
更新了个版本  ，binary 对应的C# byte[]
