### ISSUE TITLE
动态创建库和表，多库时，第二个库索引不能创建

### ISSUE THREAD

**Issue by liuhair** [donet5/SqlSugar#866]
string conn = "server=.;uid=sa;pwd=haosql;database={0}";
var db = new SqlSugarClient(new ConnectionConfig()
{
    DbType = SqlSugar.DbType.MySql,
    ConnectionString = string.Format(conn, "db1")，
    InitKeyType=InitKeyType.Attribute
});
db.DbMaintenance.CreateDatabase();

db.MappingTables.Add(typeof(Order).Name, typeof(Order).Name + 1);
db.CodeFirst.InitTables(typeof(Order));  // Order1表中有 一列设置有索引 IndexGroupNameList = new string[] { "index1" }  创建成功

var db2 = new SqlSugarClient(new ConnectionConfig()
{
    DbType = SqlSugar.DbType.MySql,
    ConnectionString = string.Format(conn, "db2")
});
db2.DbMaintenance.CreateDatabase();

db2.MappingTables.Add(typeof(Order).Name, typeof(Order).Name + 1);
db2.CodeFirst.InitTables(typeof(Order));  // Order1表中有 一列设置有索引 IndexGroupNameList = new string[] { "index1" }  db2 创建不了

**Comment by donet5** [comment]
我抽空看一下，理论上不同库的索引名称也不会冲突

**Comment by liuhair** [comment]
应该是
MySqlDbMaintenance 这个类里的
 protected override string IsAnyIndexSql
        {
            get
            {
                return "SELECT count(*) FROM information_schema.statistics WHERE index_name = '{0}'";
            }
        }
这个SQL的问题，是不是应该 table_schema 条件

**Comment by donet5** [comment]
下个版本通过 CurrentConnectionConfig.ConfigId 来区分和创建 在new sqlsugarsugarclient的时候设置configid

**Comment by donet5** [comment]
用这个 ConnectionConfig.IndexSuffix

**Comment by itcsdnnet** [comment]
[SugarColumn(Length = 50, UniqueGroupNameList = new string[] { "index1","index2","index3" })]
public string field { get; set; }
实体上联合索引这么建立不生效，只会产生一个索引字段，是因为长度问题还是什么问题？
