### ISSUE TITLE
使用了 Task.Delay 后，Ado.Transaction 属性值丢失

### ISSUE THREAD

**Issue by luesheng** [donet5/SqlSugar#867]
await Task.Delay(1);
 
_dBCom.BeginTrans();

![image](https://user-images.githubusercontent.com/69179372/105283047-a003a380-5bea-11eb-814c-79a4dc9ed310.png)

 AddScoped 依赖注入

![image](https://user-images.githubusercontent.com/69179372/105283244-04266780-5beb-11eb-85de-a57a3253a3f3.png)

**Comment by donet5** [comment]
把 await Task.Delay(1); 这个写到异步方法的后面就没问题了，

**Comment by luesheng** [comment]
> 把 await Task.Delay(1); 这个写到异步方法的后面就没问题了，
![image](https://user-images.githubusercontent.com/69179372/105320099-bcaad600-5c00-11eb-8608-01f91304b300.png)

ISqlSugarClient 是 Scoped 作用域，所以 在 Task.Delay 之前，依赖注入的 ISqlSugarClient 跨多个类事务都是存在的，但使用了 Task.Delay 之后，后面依赖注入的 ISqlSugarClient 的类，事务就丢失了，如上图，Ado = 函数求值需要运行所有线程。

public IAdo Ado => this.Context.Ado;

**Comment by donet5** [comment]
不是这个问题，我知道什么原因，你先按我说的操作

**Comment by donet5** [comment]
原理是这样的 当db线程发生变化后我会验证是不是异步，如果是异步那么我就不会new出新的sqlsugarclient对象，而你用了task.deleay让线程发生了变化我又没有办法知道你这是个异步方法，所以出现你说的问题 ，暂时这块没想到更好的设计

**Comment by donet5** [comment]
除非能有一个方法知道当前方法是不是async方法 ，这样就能更好的解决问题

**Comment by donet5** [comment]
已经找到实现方式新版本会优化掉这个问题

**Comment by donet5** [comment]
对了还有如果用到线程共享要关掉，异步不持这个玩意儿
