### ISSUE TITLE
新增表字段不能为空并且设置默认值，字段添加失败

### ISSUE THREAD

**Issue by yStar1996** [donet5/SqlSugar#869]
C# 新增表字段代码：
[SugarColumn(IsNullable = false, DefaultValue  = "0")]
public bool IsEnabled { get; set; } = false;

sqlsugar生成的脚本为：
ALTER TABLE [miniPermission] ADD [IsEnabled] bit NOT NULL

报错：One or more errors occurred. (miniPermission 创建失败,请认真检查 1、属性需要get set 2、特殊类型需要加Ignore 具体错误内容： ALTER TABLE 只允许添加满足下述条件的列: 列可以包含 Null 值；或者列具有指定的 DEFAULT 定义；或者要添加 的列是标识列或时间戳列；或者，如果前几个条件均未满足，则表必须为空以允许添加此列。不能将列"IsEnabled"添加到非空表"miniPermission"中，因为它不满足上述条件。)

如果把IsNullable 属性改为True该字段就能添加成功。

**Comment by donet5** [comment]
表删了重新建吧，这个是数据库约束
