### ISSUE TITLE
推荐使用更好的MySql与SqlServer驱动

### ISSUE THREAD

**Issue by Cloud33** [donet5/SqlSugar#870]
MySql->[MySqlConnector](https://github.com/mysql-net/MySqlConnector)
SqlServer -> [Microsoft.Data.SqlClient](https://github.com/dotnet/SqlClient)

**Comment by donet5** [comment]
NUGET有   SqlSugarCore.MySqlConnector  版本  ，至于 Microsoft.Data.SqlClient 这个后续在说

**Comment by donet5** [comment]
后续可能也支持到MySqlConnector 这个版本

**Comment by donet5** [comment]
把sqlsugarcore换成 sqlSugarCore.MySqlConnector  目前已经支持了 SqlSugarCore.MySqlConnector 和 Microsoft.Data.SqlClient

**Comment by Cloud33** [comment]
OK，谢谢

**Comment by brucehu123** [comment]
Great job
