### ISSUE TITLE
seSqlServer().ExecuteBlueCopy();     SqlBulkCopy  建议命名一致，另外是否可以直接传入Table 以及批量的参数例如：BatchSize 

### ISSUE THREAD

**Issue by duyanming** [donet5/SqlSugar#871]
.UseSqlServer().ExecuteBlueCopy();
seSqlServer().ExecuteBlueCopy();     SqlBulkCopy  建议命名一致，另外是否可以直接传入Table 以及批量的参数例如：BatchSize

**Comment by donet5** [comment]
名字不会改，支持传入 datatable  ，需要添加datatable.name  ,BatchSize目前是自带的

**Comment by donet5** [comment]
datatable必须是比较新的版本
