### ISSUE TITLE
 更新方法SetColumns中带有枚举转化时出错

### ISSUE THREAD

**Issue by ruircoder** [donet5/SqlSugar#872]
int s = (int)resultDto.Status;//枚举转化为int
  var row = this.Db.Updateable<Entity>().SetColumns(m => new Entity
  {
      EndTime = resultDto.EndTime,
      Status = s,//在前面先转化为int类型，这里赋值，执行正常
      //Status= (int)resultDto.Status//在这里转化时，sql报错，取值不在范围内
      ErrorMessage = resultDto.ErrMsg,
      JobResult = resultDto.JobResult
  }).Where(m => m.Id == id)
  .ExecuteCommand()

**Comment by donet5** [comment]
已经进步官网BUG列表 关注donet5.com发布进度
