### ISSUE TITLE
C#中调用存储过程，自定义类型参数怎么传参

### ISSUE THREAD

**Issue by PandaCuipp** [donet5/SqlSugar#874]
请教个问题：
C#中调用Oracle存储过程

CREATE OR REPLACE PROCEDURE PR_MYTEST 
(                
, itemNcId IN str_arr 
, rst OUT varchar2 
) AS 
....
存储过程入参str_arr 是自定义的 字符数组类型

请问；
在C#中使用sqlSugar怎么传入 itemNcId 入参？

我是这样写
var param = new List<SugarParameter>();
param.Add(new SugarParameter("itemNcId", new string[1] { "itemNC123456" }, DbType.Object, ParameterDirection.Input));
Ado.UseStoredProcedure().ExecuteCommandAsync("PR_MYTEST", param);
报错，
“调用 'PR_MYTEST' 时参数个数或类型错误\nORA-06550: 第 1 行, 第 7 列: \nPL/SQL: Statement ignored”

**Comment by donet5** [comment]
你写一个ADO调自定义类型存储过程的 ORACLE用例来看一下

**Comment by PandaCuipp** [comment]
> 你写一个ADO调自定义类型存储过程的 ORACLE用例来看一下

这个就是我写的测试案例，
str_arr 是自定义字符串数组类型，脚本如下：
create or replace TYPE STR_ARR  AS VARRAY(1000) OF NVARCHAR2(1000);

**Comment by PandaCuipp** [comment]
> 你写一个ADO调自定义类型存储过程的 ORACLE用例来看一下

存储过程脚本如下：
CREATE OR REPLACE PROCEDURE PR_MYTEST 
(
itemNcId IN str_arr 
, rst OUT varchar2 
) AS 

BEGIN
    rst := itemNcId(1);
       
exception
    when others then
        rst := '异常-回滚';
        rollback;
    
END PR_MYTEST;

**Comment by donet5** [comment]
你用原生的ADO.NET写一个能用的C#例子

**Comment by donet5** [comment]
长期不回复就先关闭了，有问题发新的

**Comment by PandaCuipp** [comment]
好的，我最后的解决办法是传字符串，用都逗号隔开，在存储过程内再解析为数组
