### ISSUE TITLE
SqlQueryable异步分页方法在特定情况下将泛型结果类当表来查询

### ISSUE THREAD

**Issue by goodapiyes** [donet5/SqlSugar#878]
db.Aop.OnLogExecuted = (sql, pars) =>
            {
                Console.WriteLine($"SQL：\r\n{sql}\r\n" +
                                  $"参数：{db.Utilities.SerializeObject(pars.ToDictionary(it => it.ParameterName, it => it.Value))}\r\n" +
                                  $"SQL耗时：{db.Ado.SqlExecutionTime.TotalMilliseconds}毫秒");
            };
            db.Aop.OnError = (exp) =>
            {
                Console.WriteLine($"SQL Error Message:\r\n {exp.Message + exp.StackTrace} \r\nErrorSQL:\r\n {exp.Sql} \r\n参数:\r\n{JsonConvert.SerializeObject(exp.Parametres)}\r\n");
            };
            RefAsync<int> count = 0;
            var sql = new StringBuilder(@"
                select ur.id,ur.UserId,u.Account,u.RealName,ur.ObjectType,ur.ObjectId,r.RoleName from sys_user_relation ur
                left join sys_user u
                on ur.UserId=u.Id
                left join sys_role r
                on ur.ObjectId=r.id
                where ObjectType=1");
            var result = await db.SqlQueryable<SysUserByRoleIdDto>(sql.ToString())
                .ToPageListAsync(1, 10, count);
正常情况下,SQL应该会生成:
SELECT t.* FROM  (
                select ur.id,ur.UserId,u.Account,u.RealName,ur.ObjectType,ur.ObjectId,r.RoleName from sys_user_relation ur
                left join sys_user u
                on ur.UserId=u.Id
                left join sys_role r
                on ur.ObjectId=r.id
                where ObjectType=1) t      LIMIT 0,10

但实际生成了:
SELECT t.* FROM `SysUserByRoleIdDto`     LIMIT 0,10

但如果我将OnLogExecuted中打印内容注释掉后
           db.Aop.OnLogExecuted = (sql, pars) =>
            {
                //Console.WriteLine($"SQL：\r\n{sql}\r\n" +
                //                  $"参数：{db.Utilities.SerializeObject(pars.ToDictionary(it => it.ParameterName, it => it.Value))}\r\n" +
                //                  $"SQL耗时：{db.Ado.SqlExecutionTime.TotalMilliseconds}毫秒");
            };
代码又正常了,或者不传递count,也可以正常得到返回结果.

**Comment by donet5** [comment]
先确定版本是不是最新版本，给我一个可以重现的用例 ，也可能是你的DB跨线程使用引起的问题

**Comment by goodapiyes** [comment]
<PackageReference Include="SqlSugarCore" Version="5.0.0.18" /&gt;
版本不是最新版, 是5.0.0.18.
我用asp.net core mvc示例HomeController里增加了可重现的用例.
我刚刚升级到5.0.0.2.6版本后,正常了.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "donet5/SqlSugar"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月4日(星期四) 中午12:50
收件人:&nbsp;"donet5/SqlSugar"<SqlSugar@noreply.github.com&gt;;
抄送:&nbsp;"ccoder"<2098240977@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [donet5/SqlSugar] SqlQueryable异步分页方法在特定情况下将泛型结果类当表来查询 (#878)





 
先确定版本是不是最新版本，给我一个可以重现的用例 ，也可能是你的DB跨线程使用引起的问题

**Comment by donet5** [comment]
新版本能用是吗那就关了吧

**Comment by goodapiyes** [comment]
> 新版本能用是吗那就关了吧

好的,我想了解下新版本具体是什么问题,会导致这样的情况出现.
