### ISSUE TITLE
升级成 .Net 5 后，DateTime 时区问题

### ISSUE THREAD

**Issue by gmbzero** [donet5/SqlSugar#880]
English Message : Entity mapping error.Can't cast database type time without time zone to DateTime ↵Chinese Message

**Comment by donet5** [comment]
在链接MySQL的字符串中添加：Convert Zero Datetime=True 和 Allow Zero Datetime=True两个属性；

**Comment by donet5** [comment]
文档有介绍 http://www.donet5.com/Home/Doc?typeId=1219

**Comment by gmbzero** [comment]
> 文档有介绍 http://www.donet5.com/Home/Doc?typeId=1219

我的数据库是 postgresql ，表字段类型是 time 类型

**Comment by gmbzero** [comment]
> 文档有介绍 http://www.donet5.com/Home/Doc?typeId=1219

![image](https://user-images.githubusercontent.com/43951310/110417516-b8634b00-80d0-11eb-8d08-5f49ca8a63af.png)

**Comment by gmbzero** [comment]
> > 文档有介绍 http://www.donet5.com/Home/Doc?typeId=1219
> 
> 我的数据库是 postgresql ，表字段类型是 time 类型

![image](https://user-images.githubusercontent.com/43951310/110420222-e13a0f00-80d5-11eb-8030-68627f89f32b.png)


 case CSharpDataType.DateTime:
                    CheckType(bind.DateThrow, bindProperyTypeName, validPropertyName, propertyName);
                    if (bindProperyTypeName == "datetime")
                        method = isNullableType ? getConvertDateTime : getDateTime;
                    if (bindProperyTypeName == "datetime" && (dbTypeName.ToLower() == "time" || dbTypeName.ToLower() == "time with time zone" || dbTypeName.ToLower() == "time without time zone"))
                        method = isNullableType ? getConvertTime : getTime;
                    if (bindProperyTypeName == "datetimeoffset")
                        method = isNullableType ? getConvertdatetimeoffset : getdatetimeoffset;
                    break;

**Comment by donet5** [comment]
这边我会验证一下的 ，还有你提供一下驱动版本号

**Comment by gmbzero** [comment]
Postgresql版本：PostgreSQL 11.10 on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
SqlSugarCore版本：5.0.2.6
Npgsql：4.1.5
