### ISSUE TITLE
sqlsugar使用mycat的问题

### ISSUE THREAD

**Issue by tangweidali** [donet5/SqlSugar#884]
![QCNUPJAZ@J$F22{}@ _DC X](https://user-images.githubusercontent.com/57385890/111247529-1d73ef00-8643-11eb-8d59-b24e23e09be8.png)
sqlsugar使用mycat的问题

这个问题是mycat的，与sqlsugar无关，

解决方法是放弃引用mysql.data.dll转而引pomelo.dll，我尝试引用pomelo，结果还是报错

我在社区中提问，有大神回答说sqlsugar可以用mycat，请问是怎么用的？

mycal1.6.7    sqlsugar5.0.26

**Comment by tangweidali** [comment]
补充一下，ex.Message错误是：给定的关键字不在字典中

**Comment by donet5** [comment]
确实有人用过

**Comment by donet5** [comment]
你这个错应该是连接字符串的错

**Comment by donet5** [comment]
你可以用MYSQL.DATA  mysqlconnection(字符串).open()测试通过
