### ISSUE TITLE
请增加 pgsql对 float[] 的支持

### ISSUE THREAD

**Issue by pkingwsd** [donet5/SqlSugar#886]
float[]      NpgsqlDbType = NpgsqlDbType.Array | NpgsqlDbType.Real;---- 我已经测试了没问题。
测试版本 Npgsql, Version=5.0.3.0,

请增加到。

static readonly Dictionary<Type, NpgsqlDbType> ArrayMapping = new Dictionary<Type, NpgsqlDbType>()
        {
            { typeof(int[]),NpgsqlDbType.Integer},
            { typeof(short[]),NpgsqlDbType.Smallint},
            { typeof(long[]),NpgsqlDbType.Bigint},
            { typeof(decimal[]),NpgsqlDbType.Numeric},
            { typeof(char[]),NpgsqlDbType.Text},
            { typeof(byte[]),NpgsqlDbType.Bytea},
            { typeof(bool[]),NpgsqlDbType.Boolean},
            {typeof(DateTime[]),NpgsqlDbType.Date},

            { typeof(int?[]),NpgsqlDbType.Integer},
            { typeof(short?[]),NpgsqlDbType.Smallint},
            { typeof(long?[]),NpgsqlDbType.Bigint},
            { typeof(decimal?[]),NpgsqlDbType.Numeric},
            { typeof(char?[]),NpgsqlDbType.Text},
            { typeof(byte?[]),NpgsqlDbType.Bytea},
            { typeof(bool?[]),NpgsqlDbType.Boolean},
            {typeof(DateTime?[]),NpgsqlDbType.Date},

             { typeof(string[]), NpgsqlDbType.Text},
        };
    }

**Comment by donet5** [comment]
OK

**Comment by donet5** [comment]
近期发布本地测试通过
