### ISSUE TITLE
反馈一个使用中遇到的bug

### ISSUE THREAD

**Issue by LoveAuggie** [donet5/SqlSugar#887]
设置如下:
1. 设置了全局过滤器，如下：
     db.QueryFilter.Add(new SqlSugar.SqlFilterItem()
                            {
                                FilterValue = filterDb =>
                                {
                                    return new SqlFilterResult() { Sql = " sOrgId=@sOrgId", Parameters = new { sOrgId = '111'} };
                                },
                                IsJoinQuery = false
                            });
2.  在使用ToPageListAsync(pageIndex, pageSize, total) 时会出错，提示parameter sOrgId 已存在，在调试中，可以看到当运行时，paramter中有多个sOrgId的参数。

若将QueryFilter修改为纯sql，没有paramter设置，则不会报错，或者分页不带Total时也不会报错。
初步怀疑应该是调用Total前的Clone()方法导致的问题。
请查看~

**Comment by donet5** [comment]
好的近期修复

**Comment by donet5** [comment]
最新版本没有重现


 db.QueryFilter.Add(new SqlFilterItem()
            {
              
                FilterValue = it =>
                {
                    //Writable logic
                    return new SqlFilterResult() { Sql = " id=@id ", Parameters= new { id=1} };
                },
                IsJoinQuery = false //单表查询生效
            });
            var s14 = db.Queryable<Order>().ToPageListAsync(1,2,3);
            s14.Wait();


这个是我的代码 ，是不是你的参数和你的查询参数正好重叠了

**Comment by donet5** [comment]
SELECT COUNT(1) FROM (SELECT [Id],[Name],[Price],[CreateTime],[CustomId] FROM [Order]  WHERE  id=@id  ) CountTable
@id:1
SELECT * FROM (SELECT [Id],[Name],[Price],[CreateTime],[CustomId],ROW_NUMBER() OVER( ORDER BY GetDate() ) AS RowIndex  FROM [Order]  WHERE  id=@id  ) T WHERE RowIndex BETWEEN 1 AND 2
@id:1

**Comment by donet5** [comment]
已重现了MYSQL会出错，已修复 最近同步
