### ISSUE TITLE
sqlsugar 连oracle的问题

### ISSUE THREAD

**Issue by solobg** [donet5/SqlSugar#889]
您好，
有时候会报
SqlSugar.SqlSugarException: English Message : Connection open error . ORA-12545: Network Transport: Unable to resolve connect hostname
Chinese Message :  连接数据库过程中发生错误，检查服务器是否正常连接字符串是否正确，实在找不到原因请先Google错误信息：ORA-12545: Network Transport: Unable to resolve connect hostname. 
![image](https://user-images.githubusercontent.com/7735458/111935689-f31ca880-8afe-11eb-8bb5-36e33cc2359a.png)

**Comment by donet5** [comment]
连接字符串或者服务器问题
