### ISSUE TITLE
实体的泛型约束，可以去除new()无参约束么

### ISSUE THREAD

**Issue by zhangzw218** [donet5/SqlSugar#890]
主要是因为，公司使用AbpvNext框架，内部的领域模型，要求隐藏无参构造，创建实体就必须传参。
比如一个实体是这样的：
`  

    public class PermissionGrant : Entity<Guid>, IMultiTenant
    {
        public virtual Guid? TenantId { get; protected set; }

        [NotNull]
        public virtual string Name { get; protected set; }

        [NotNull]
        public virtual string ProviderName { get; protected set; }

        [CanBeNull]
        public virtual string ProviderKey { get; protected internal set; }

        protected PermissionGrant()
        {

        }

        public PermissionGrant(
            Guid id,
            [NotNull] string name,
            [NotNull] string providerName ,
            [CanBeNull] string providerKey,
            Guid? tenantId = null)
        {
            Check.NotNull(name, nameof(name));

            Id = id;
            Name = Check.NotNullOrWhiteSpace(name, nameof(name));
            ProviderName = Check.NotNullOrWhiteSpace(providerName, nameof(providerName));
            ProviderKey = providerKey;
            TenantId = tenantId;
        }
    }
}

`
大概是这样的，所有实体的无参构造都是protected，我尝试将这个实体放到SqlSugar中就无法使用，因为有无参约束。
这个有办法处理么。

**Comment by donet5** [comment]
去不了 目前的设计
