### ISSUE TITLE
希望添加一个函数实体增删改查时可以更改表名

### ISSUE THREAD

**Issue by h619633675** [donet5/SqlSugar#895]
在实际使用中，有时候会出现一些表如后缀不一样但是表结构一摸一样的表。
实体使用很不方便，希望添加一个函数实体增删改查时可以更改表名

**Comment by donet5** [comment]
insertable(list).As("表名")    用AS就行了

**Comment by h619633675** [comment]
哦哦哦，谢谢，前面没发现它
