### ISSUE TITLE
属性设置默认值DefaultValue，数据库表变更时有问题

### ISSUE THREAD

**Issue by apgk** [donet5/SqlSugar#898]
实体设置如下，
 [SugarColumn(ColumnDataType = "datetime", ColumnDescription = "创建日期", DefaultValue = "getdate()")]
  public DateTime CreateTime { get; set; }

数据库表 默认值生成会是  (‘getdate()‘)

这样数据库变更字段时就会报 时间的默认值不对。

**Comment by donet5** [comment]
变更什么描述清楚点，什么数据库

**Comment by donet5** [comment]
要改字段用ORM去改吧  ，你这个手动改引起的错我这边不能控制

**Comment by ly04405** [comment]
我也遇到类似问题：
表名：site，字段名：genomicPloidy，字段类型：int
`db.DbMaintenance.AddDefaultValue("site", "genomicPloidy", "2");`
生成的 SQL 语句为：
`ALTER TABLE [site] ADD DEFAULT '2' FOR [genomicPloidy]
// 应该是 ALTER TABLE [site] ADD DEFAULT 2 FOR [genomicPloidy]
`
数据库中默认值为   ('2')，应该是   ((2))
