### ISSUE TITLE
datetime tostring()格式化问题

### ISSUE THREAD

**Issue by solobg** [donet5/SqlSugar#901]
` var list = query.Select(a => new { date =  a.CreateTime.ToString("yyyy-MM-dd") })`

例：date 格式化后的日期为'2021-04-7' ， 如果天小于10不会补0？

**Comment by donet5** [comment]
后续优化

**Comment by donet5** [comment]
var list = query.Select(a => new { date = a.CreateTime.ToString() })
.Mapper(it=> Convert.toddatetime(it.createtime).ToString("yyyy-MM-dd"))  你可以先这样写

**Comment by donet5** [comment]
已修改 今天晚点发布
