### ISSUE TITLE
字段IsJson查询生成Sql语句问题

### ISSUE THREAD

**Issue by feiyit** [donet5/SqlSugar#902]
字段定义：
 [SqlSugar.SugarColumn (ColumnDataType = "varchar(50)", IsJson = true)]  
    public List<int> Attr { get; set; }

查询方法：
where.And (m => m.Attr.Contains(param.Attr));

生成的Sql语句：
SELECT Count(*) FROM `cms_article`  WHERE (( 1 = 1 ) AND NOT (1=2) ) 

Attr在数据库是varchar类型
不知道为什么生成的sql是1=2,    2=是我传入的     attr怎么变成1了呢？

是不支持这种写法吗？

**Comment by donet5** [comment]
这个肯定不支持 ， 还没这么牛逼把JSON对象 当LINQ查询
