### ISSUE TITLE
提示代码有问题

### ISSUE THREAD

**Issue by KiritoStudio** [donet5/SqlSugar#903]
QueryBuilder代码exception有bug
`Check.Exception(!string.IsNullOrEmpty(this.TableShortName) && resolveExpress.SingleTableNameSubqueryShortName != this.TableShortName, "{0} and {1} need same name");`

**Comment by donet5** [comment]
应该是什么样子的

**Comment by KiritoStudio** [comment]
@donet5 https://github.com/donet5/SqlSugar/pull/904 已经pull代码了，之前是报的一个format error的错误，调了半天发现是形参就是table short name，这个问题发生在子查询的表同时是父查询的表，并且形参不同才会出现。

**Comment by donet5** [comment]
已合并
