### ISSUE TITLE
sql 查询疑问

### ISSUE THREAD

**Issue by h619633675** [donet5/SqlSugar#905]
1. 在 SqlFunc 中没有看到 Abs 这类函数，不知道在哪里有
2. 在查询时 .Select(a => a.status),.First() 其中的 status 为枚举类会报错 int32 不能转换为枚举，整个类取出又不会报错

**Comment by donet5** [comment]
这2个后期优后吧
1.你可以先用 扩展函数实现，自带的还没有加
2.你可以select(it=>convet.toint32(a.stauts))

**Comment by donet5** [comment]
扩展函数地址 https://www.donet5.com/Home/Doc?typeId=1225

**Comment by h619633675** [comment]
好的谢谢

**Comment by donet5** [comment]
明天发布

**Comment by h619633675** [comment]
灰常感谢，辛苦大佬，大佬喝阔落
