### ISSUE TITLE
为什么帮助文档感觉内容很散啊

### ISSUE THREAD

**Issue by h619633675** [donet5/SqlSugar#909]
https://www.donet5.com/Doc/8/1124
像这个，找了好久才找到 两个 Queryable 合并查出， 5 的文档貌似没有

**Comment by donet5** [comment]
你那是4的文档  ，这才是5 https://www.donet5.com/Home/Doc?typeId=2308

**Comment by h619633675** [comment]
额， 我的意思是&nbsp;https://www.donet5.com/Doc/8/1124 这个页面的这个标题的&nbsp;6.二个Queryable的Join(4.6.0.9)
我并不知道在 5 的哪里能找到，我翻看了几遍最后 google 搜索 sqlsugar 二个Queryable的Join 才看到你4的版本的有这个




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月10日(星期一) 上午10:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [donet5/SqlSugar] 为什么帮助文档感觉内容很散啊 (#909)





 
你那是4的文档  ，这才是5 https://www.donet5.com/Home/Doc?typeId=2308

**Comment by donet5** [comment]
把我上面的链接好好看看，里面有

**Comment by donet5** [comment]
以查询目录为准
