### ISSUE TITLE
根据表达式 删除生成sql，直接抛异常

### ISSUE THREAD

**Issue by apgk** [donet5/SqlSugar#910]
我的表设计 字段是 Id  Name PId PIdLIST  
数据演示  
Id Name  PID  PIDList
1  父级    0      ,0,1,  
2  子级    1      ,0,1,2,
我想删除 父级时顺便删除子级
var exp = Expressionable.Create<TreeEntity>();
          var temp=new List<string>(){",1,"};
            foreach (var item in temp)
            {
                exp.Or(c => c.ParentList.Contains(item));
            }
            var exps = exp.ToExpression();
            var sss = _context.Db.Deleteable<TreeEntity>().Where(exps);
            var sql = sss.DeleteBuilder.ToSqlString();
报错了 System.NullReferenceException:“Object reference not set to an instance of an object.”
 这句直接报错       var sql = sss.DeleteBuilder.ToSqlString();

目前需求就是根据传入的id 删除旗下所有，类似一个递归删除，想看下这个生成的sql.没想到直接报错

**Comment by donet5** [comment]
删除不支持二级对象  c.ParentList
