### ISSUE TITLE
SqlSugar初体验之SQLite

### ISSUE THREAD

**Issue by ohsorry** [donet5/SqlSugar#913]
接触sqlsugar一共不到5小时，刚开始尝试使用就发现问题。
首先看到文档有这段文字：
![s1](https://user-images.githubusercontent.com/6219683/119249581-37dec180-bbcc-11eb-8d73-9f34cf98af8d.png)
类似的文字不止一次看到过，所以想必SqlSugar对性能做了极致的优化，至少是**优化**的！

然而这种sql查询真让人大跌眼镜，首先是`Any()`。文档描述：
![s2](https://user-images.githubusercontent.com/6219683/119249655-e4b93e80-bbcc-11eb-8c2e-689c45b89047.png)
尝试`db.Queryable<Domain.MemoryPiece>().Any(w => w.MemoryPieceId == id);`后输出的sql竟然是
``` sql
select count(1) from(select 所有字段 from 表 where id=id))
```
判断是否存在记录，随便就能写出更好的sql吧？

然后是更新字段：
![s3](https://user-images.githubusercontent.com/6219683/119249728-73c65680-bbcd-11eb-8290-f4f18e3d3f13.png)
然而当`SetColumnsIF`的条件都是false时，这条sql并没有忽略执行或者有个set 1=1之类的，而是更新了这个表的**所有字段**！
``` c#
        public int EditePiece(int pid, string name="", string remark = "")
        {
            using (var db = _databaseService.CreateDbClient())
            {
                return db.Updateable<Domain.MemoryPiece>()
                    .SetColumnsIF(!string.IsNullOrEmpty(name), p => p.Name == name) // 这样都false会全部更新槽
                    .SetColumnsIF(!string.IsNullOrEmpty(remark), p => p.Remark == remark)//这样都false会全部更新槽
                    .Where(p => p.Id == pid)
                    .ExecuteCommand();

            }
        }

 ```
以上，当name和remark都空时产生的sql是修改所有字段！

先到这吧。接下几天应该会继续尝试sqlsugar，帖子会更新。

**Comment by lianyitj** [comment]
我也是刚尝试，这个更新所有字段，更新成什么了呢？都给清了？要真有这么问题就太可怕了

**Comment by donet5** [comment]
`        public IUpdateable<T> SetColumnsIF(bool isUpdateColumns, Expression<Func<T, bool>> columns)
        {
            ThrowUpdateByObject();
            if (isUpdateColumns)
                SetColumns(columns);
            return this;
        }
        public IUpdateable<T> SetColumnsIF(bool isUpdateColumns, Expression<Func<T, T>> columns)
        {
            ThrowUpdateByObject();
            if (isUpdateColumns)
                SetColumns(columns);
            return this;
        }`
自个检查逻辑确认有问题在提出来

**Comment by ohsorry** [comment]
上面的双`SetColumnsIF`产生的sql是这样的：
![s3](https://user-images.githubusercontent.com/6219683/119304288-a178d180-bc99-11eb-9bef-d2856efccda1.png)

换个写法，就会拼接正确的sql:
![s2](https://user-images.githubusercontent.com/6219683/119304354-b7869200-bc99-11eb-8152-aa269b527a1d.png)
输出：
![m3](https://user-images.githubusercontent.com/6219683/119304437-d08f4300-bc99-11eb-819a-47d6abc87647.png)

代码有什么问题么？

**Comment by donet5** [comment]
保证至少有一列 就没问题

**Comment by donet5** [comment]
一列没有SQL语句会报错 set  空
