### ISSUE TITLE
系统中有多个数据库,同时操作.

### ISSUE THREAD

**Issue by easy999000** [donet5/SqlSugar#921]
文档多租户

_Originally posted by @donet5 in https://github.com/donet5/SqlSugar/issues/915#issuecomment-846982647_

我仔细的看了多租户的文档,多租户这个功能和我需要用到的并不一样.
我的一个系统有多个数据库,里面存放着不同的表.
当我使用多租户的模式的时候,我是把整个 SqlSugarClient 对象的连接切换到其中的一个db上去了.那么对于其他db的查询就要报错了.
我是想实现 同一个SqlSugarClient 对象,同时可以从不同的数据库里面查找数据.
比如a1表自动的到a库里面去查找,b1表自动的到b数据库里面去查找.
现在这种情况,多租户的功能,不论我把数据库切换到哪个指向上,都会有一个查询报错.

**Comment by easy999000** [comment]
我的系统有3个数据库(a,b,c)一共15张表.
我实例化一个SqlSugarClient 对象 DB 后(全局对象).  我要从这3个数据库中的不同表里面查询数据.
如何使用多租户.  任何一个方法把 Db的连接指向随便切走后, 可能导致其他正在执行查询的方法报错,因为当前连接的数据库并没有指定的表.

如上需求我应该怎么处理呢.

**Comment by easy999000** [comment]
其实就是一个系统中,有多个数据库的, 建议最佳操作方式是怎么样的.

**Comment by donet5** [comment]
https://www.donet5.com/Home/Doc?typeId=2246

**Comment by easy999000** [comment]
> https://www.donet5.com/Home/Doc?typeId=2246

这个并不能解决我的问题,算了,我自己研究吧
