### ISSUE TITLE
SqlSugarAccessory.cs中CopyEntityInfo拷贝问题

### ISSUE THREAD

**Issue by guanguanchuangyu** [donet5/SqlSugar#922]
https://github.com/donet5/SqlSugar/blob/SqlSugar5/Src/Asp.Net/SqlSugar/Abstract/SugarProvider/SqlSugarAccessory.cs
166行函数中拷贝实例用途是啥？

**Comment by donet5** [comment]
新建一个副本这样不影响缓存里面的对象

**Comment by guanguanchuangyu** [comment]
![image](https://user-images.githubusercontent.com/25916858/121642898-b6d86300-cac3-11eb-834c-64516155d74f.png)
这样就可以了？
