### ISSUE TITLE
CreateDatabase 创建SqlServer路径问题

### ISSUE THREAD

**Issue by zonecolour** [donet5/SqlSugar#924]
在 Src/Asp.Net/SqlSugar/Realization/SqlServer/DbMaintenance/SqlServerDbMaintenance.cs 324行，
如果指定创建数据库路径，根本没有必要判断路径是否存在，因为我部署的web服务器和sqlserver服务器不是同一台机器，
假设我定义路径为D：盘，但我的web服务器上只有C：盘，数据库服务器上才有D：盘，这样判断路径就会造成失败，
但跳过判断，是可以执行成功的，建议去掉这段代码或另作判断

public override bool CreateDatabase(string databaseName, string databaseDirectory = null)
{
**if (databaseDirectory != null)
{//建议去掉路径判断，可能web服务器与数据库服务器盘符不同
if (!FileHelper.IsExistDirectory(databaseDirectory))
{
FileHelper.CreateDirectory(databaseDirectory);
}
}**
var oldDatabaseName = this.Context.Ado.Connection.Database;
var connection = this.Context.CurrentConnectionConfig.ConnectionString;
connection = connection.Replace(oldDatabaseName, "master");
var newDb = new SqlSugarClient(new ConnectionConfig()
{
DbType = this.Context.CurrentConnectionConfig.DbType,
IsAutoCloseConnection = true,
ConnectionString = connection
});
if (!GetDataBaseList(newDb).Any(it => it.Equals(databaseName, StringComparison.CurrentCultureIgnoreCase)))
{
var sql = CreateDataBaseSql;
if (databaseDirectory.HasValue())
{
sql += @"on primary
(
name = N'{0}',
filename = N'{1}{0}.mdf',
size = 10mb,
maxsize = 100mb,
filegrowth = 1mb
),
(
name = N'{0}_ndf',
filename = N'{1}{0}.ndf',
size = 10mb,
maxsize = 100mb,
filegrowth = 10 %
)
log on
(
name = N'{0}_log',
filename = N'{1}{0}.ldf',
size = 100mb,
maxsize = 1gb,
filegrowth = 10mb
); ";
}
newDb.Ado.ExecuteCommand(string.Format(sql, databaseName, databaseDirectory));
}
return true;
}

**Comment by donet5** [comment]
很少在服务器上去建库特殊情况你就搞一样的目录吧

**Comment by zonecolour** [comment]
关键是数据库服务器上连盘符都没有，如何创建相同目录呢，动态建库我主要是为了日志服务，我也不想去修改源码，但实际情况不允许啊

**Comment by donet5** [comment]
我加个try吧 找不到就不处理
