### ISSUE TITLE
同一个 SqlSugarProvider 对象,在多个线程上,并发操作查询插入,会有问题吗

### ISSUE THREAD

**Issue by easy999000** [donet5/SqlSugar#927]
我发现一个事情就是,直接在SqlSugarClient 上查询的话, 方法会判断,是否是同一个线程,如果不是同一个线程就创建新的 SqlSugarProvider 对象,再查询.这样可以保证不会出现并发问题.

但是通过 GetConnection 获取的 SqlSugarProvider,无论几个线程都是同一个对象,那这样岂不是会出现,并发问题
大佬,能解答一下吗, 这块设计的时候是怎么考虑的呢
图一是 SqlSugarClient 普通查询获取 SqlSugarProvider对象
图二是GetConnection  获取 SqlSugarProvider对象

![image](https://user-images.githubusercontent.com/45551150/123196545-b46f0380-d4dc-11eb-9c16-9306474220a7.png)

![image](https://user-images.githubusercontent.com/45551150/123196562-ba64e480-d4dc-11eb-8bab-20e06971d250.png)

**Comment by donet5** [comment]
有问题在发，目前相当稳定 NUGET月下载量过万
