### ISSUE TITLE
SetColumnsIF 如果全部未达成会导致更新所有字段

### ISSUE THREAD

**Issue by lihelin456** [donet5/SqlSugar#929]

**Comment by lihelin456** [comment]
_gUserDal.Db.Updateable<GUser>()
                .SetColumnsIF(!dto.NickName.IsNullOrEmpty(), c => c.NickName == dto.NickName)
                .SetColumnsIF(dto.BirthdayTime != null, c => c.BirthdayTime == dto.BirthdayTime)
                .SetColumnsIF(dto.MainPic != null, c => c.MainPic == dto.MainPic)
                .Where(c => c.GUserId == _gUserId)
                .ExecuteCommand();

如果全部条件都是false 会导致更新所有字段

**Comment by donet5** [comment]
要保证有一列

**Comment by donet5** [comment]
不然会报错

**Comment by lihelin456** [comment]
> 要保证有一列

这种如果全部条件未达成throw 一个错误或者不更新会稍微好点吧。因为执行之后肯定是错误的预期
