### ISSUE TITLE
项目里总是报连接字符串的错误

### ISSUE THREAD

**Issue by lilu-ops** [donet5/SqlSugar#930]
项目里总是报连接字符串的错误，我查看了偶发性错误的文档，我感觉我这边的用法也没有问题，打印出的字符串看着也没有问题，两个项目用法一样另一个项目里没有出现这样的问题，操作是一个方法中有一个删除和一个写入

**Comment by donet5** [comment]
NUGET引用问题

**Comment by lilu-ops** [comment]
是需要更新一下NUGET包吗？现使用的是5.0.1.4版本

**Comment by lilu-ops** [comment]
> NUGET引用问题

是需要更新一下NUGET包吗？现在使用的是5.0.1.4版本
