### ISSUE TITLE
SqlQueryable<object>(strSql).AddParameters中的参数能否支持JArray？

### ISSUE THREAD

**Issue by bryanli2018** [donet5/SqlSugar#932]
SQL如下：
WHERE 1 = 1
AND u.DeleteFlag = 0
AND u.UserID IN (@UserID)

传参如下：
![image](https://user-images.githubusercontent.com/39940961/125575214-0360b908-cf1a-4e52-95ad-77e910c183fc.png)

拼接出来的IN()不正确并且报错如下：
![image](https://user-images.githubusercontent.com/39940961/125575680-98afca28-ee25-4604-819e-be8324a4d7af.png)

数据库SQLSERVER 2008R2

**Comment by donet5** [comment]
目前不支持

**Comment by donet5** [comment]
可以支持字典

**Comment by bryanli2018** [comment]
貌似这么传数组有点奇怪
var dt = db.SqlQueryable<object>(strSql).AddParameters(new {UserID = new string[] {"A1","A2","A3" } }).OrderBy(strOrderBy).ToDataTablePage(pageIndex, pageSize, ref cnt);

执行COUNT查询语句调试如下图：
![image](https://user-images.githubusercontent.com/39940961/125639695-16bde3a9-7caf-4a34-a51d-47cd74a60050.png)

执行分页查询语句调试如下图：
![image](https://user-images.githubusercontent.com/39940961/125640148-68f5ed5e-fcd1-44e5-af87-d6e235b88802.png)

**Comment by bryanli2018** [comment]
经查是走到这里时参数值被清掉了。
![image](https://user-images.githubusercontent.com/39940961/125714260-81f2698e-3cca-45bc-b595-b39e751f5148.png)

**Comment by donet5** [comment]
字典里面在传 数组有问题是吗？下个版本修复

**Comment by donet5** [comment]
select * from [order] where  id in ('1','2')

 var dt = db.Ado.GetDataTable("select * from [order] where  id in (@id)",  new Dictionary<string, object>() {
                {"id",new string[]{ "1","2"} } 
              
            });
没发现问题

**Comment by donet5** [comment]
生成的SQL也正确

**Comment by bryanli2018** [comment]
应该跟字典型传数组没关系，而是跟分页查询有关，请验证下面的代码：
int cnt = 0;
var ret = db.SqlQueryable<object>("select * from [order] where id in (@id) ").AddParameters(new { id = new string[] { "1", "2" } }).ToDataTablePage(0, 2, ref cnt);

**Comment by donet5** [comment]
OK已修复  NUGET下个版本更新    datatable分页独有问题
