### ISSUE TITLE
PostgreSQL text[] support.

### ISSUE THREAD

**Issue by BurakCinar07** [donet5/SqlSugar#937]
Is there a way to handle text[] or varchar[] columns? I tried to work around with varius ways but could not figure out.
If there isn't a way to handle text[] can you add such a feature?

**Comment by donet5** [comment]
The next time the support

**Comment by BurakCinar07** [comment]
Looking forward to this feature. Thank you.

**Comment by donet5** [comment]
`  [SqlSugar.SugarColumn(IsArray = true, ColumnDataType = "text[]")]
   public string[] colums { get; set; }


 db.Insertable(new TestA() { colums = new string[] { "a" } }).ExecuteCommand();
  var xx = db.Queryable<TestA>().ToList();
`

Like I did before

**Comment by BurakCinar07** [comment]
This doesn't work. I created a column like you did 
[SugarColumn(ColumnName = "test",  IsArray = true, ColumnDataType = "text[]")]
public string[] Test { get; set; }

And I used insertable like below 
dbt.Insertable(new LectureEntity
{
    ProductId = productId,
    LanguageCode = languageCode,
    Title = title,
    Slug = slug,
    CategoryId = categoryId,
    Test = new[] {"asdfasdf"},
    LevelId = levelId,
    IsActive = false,
}).IgnoreColumns(l => new {l.Acquirements, l.Requirements})
.EnableDiffLogEvent(user)
.ExecuteReturnIdentity();

From what I gather below error message column named Test doesn't have Postgresql array literal value. 

Npgsql error message:
 Exception data:
          Severity: ERROR
          SqlState: 22P02
          MessageText: malformed array literal: "asdfasdf"
          Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
          Position: 290
          File: arrayfuncs.c
          Line: 314
          Routine: array_in
