### ISSUE TITLE
WhereClass方法在Postgresql中没有加入FieldValueConvertFunc，导致报错Npgsql.PostgresException:“42883: operator does not exist: bigint = text”

### ISSUE THREAD

**Issue by 027kaka** [donet5/SqlSugar#938]
if (this.Context.CurrentConnectionConfig.DbType == DbType.PostgreSQL) 
                        {
                            data.Value.FieldValueConvertFunc = it =>
                            {
                                return UtilMethods.ChangeType2(it, value.GetType());
                            };
                        }

**Comment by donet5** [comment]
WhereClassByPrimaryKey 这个方法有加 ，你这个我本地也加一下个版本修复
