### ISSUE TITLE
有Type但没有泛型变量无法查询

### ISSUE THREAD

**Issue by PAULWONGHZ** [donet5/SqlSugar#945]
private List load(Type classType, long id) 
  {
      var l = db.Queryable<???>().Where("id=@id", new {id = id})
          .ToList();
      return l;
}

这个方法无法正常运行，因为我只有Type，拿不到泛型变量，官方什么时候能支持一下？

**Comment by donet5** [comment]
`var l = db.Queryable<object>().As(type.Name).Where("id=@id", new {id = id})`

**Comment by PAULWONGHZ** [comment]
![image](https://user-images.githubusercontent.com/1744317/128985203-18eb73e0-1c85-4dd8-88bf-3966bb5120b5.png)
按照你的写法出来是个List<ExpandoObject >， 而我希望是List<DbUser>

**Comment by donet5** [comment]
你应该适合学习一下泛型 https://www.donet5.com/Doc/20

**Comment by donet5** [comment]
通过泛型去封装
