### ISSUE TITLE
关于字段序列化问题

### ISSUE THREAD

**Issue by PAULWONGHZ** [donet5/SqlSugar#946]
[SugarTable("Test")]
    public class Test
    {
        [SugarColumn(IsPrimaryKey = true)]
        public long Id { get; set; }

        [SugarColumn(IsJson = true)] //这里现在只能以json字符串入库，能不能用自定义的二进制序列化工具入库(比如protobuff等)？
        public DbUser user { get; set; }
    }

**Comment by donet5** [comment]
这个你只能全局设置JSON.NET

**Comment by donet5** [comment]
是可以重定义
     ConnectionString = Config.ConnectionString,//Master Connection
                DbType = DbType.SqlServer,
                InitKeyType = InitKeyType.Attribute,
                IsAutoCloseConnection = true ,ConfigureExternalServices=new ConfigureExternalServices() { 
                 SerializeService=new SqlSugar.SerializeService()
                }
 不过用完了最好把配置改回来

**Comment by PAULWONGHZ** [comment]
这太麻烦了， 建议在SugarColumn加个转换接口吧
