### ISSUE TITLE
调用数据库更新后数据未改变

### ISSUE THREAD

**Issue by ddddtse** [donet5/SqlSugar#951]
代码如下：
```c#

//为tUpdatedTest中的每个item的某一属性赋值
 ...

//更新数据库与界面
Task.Run(() =>
            {
                var db = DB.GetInstance();
                tUpdatedTest.ForEach(item =>
                {
                    db.Updateable(item).ExecuteCommand();
                    _updateTestStatus?.Invoke(item);
                });
            });
```
界面显示`tUpdatedTest`的值显示有更新，因此判断属性赋值没有问题，且`_updateTestStatus?.Invoke(item)`执行成功。
但查看数据库时，数据库中的数据中此属性没有更新。

请问是我调用`Updateable`的方式不对吗？或者您有什么建议？

**Comment by donet5** [comment]
Task.Run(() =>
            {
                   var db = DB.GetInstance();
                    db.Updateable(tUpdatedTest ).ExecuteCommand();
            });
更新只要这么写就行了，如果没有更新就看你传进去的 list<T> 有没有设置主键或者数据是否正确

**Comment by ddddtse** [comment]
@donet5 谢谢，那我使用的方法没有错。我看看是不是其他地方有更改到数据，又把数据给置空了。;)

**Comment by donet5** [comment]
没问题就先关了有问题在提发新的ISSUE
