### ISSUE TITLE
postgresql只要执行返回跟id相关的方法,都会以小写id去查询返回,并不会按照设置了PgSqlIsAutoToLower = false使用Id进行查询

### ISSUE THREAD

**Issue by pigwing** [donet5/SqlSugar#953]
ExecuteReturnBigIdentityAsync 等方法,postgresql设置了PgSqlIsAutoToLower = false不自动小写,但是Id依然会产生id小写.

**Comment by pigwing** [comment]
![image](https://user-images.githubusercontent.com/8393545/130749698-fd48a850-65d2-4bba-bd9b-41b2c7791826.png)

**Comment by donet5** [comment]
不规范表，我只能作兼容处理，已知的情况可以发给我

**Comment by pigwing** [comment]
public class MyEntity
    {
        [SugarColumn(IsPrimaryKey = true, IsIdentity = true, ColumnName = "Id")]
        public long Id { get; set; }
        public string A {get;set}
    }

SqlSugarClient.Insertable<MyEntity>(entityObj).ExecuteReturnBigIdentityAsync()

**Comment by pigwing** [comment]
@donet5 针对postgresql的情况,默认是区分大小写的.然后也配置了PgSqlIsAutoToLower = false,其他都没问题,就是需要插入并且返回自增长的Id的时候,把Id直接小写成了id,导致postgresql报id字段不存在,应该是要用Id这个字段的.

**Comment by donet5** [comment]
本地已解决 周一前会同步
