### ISSUE TITLE
查询字段里用到了数据库函数

### ISSUE THREAD

**Issue by overfreedom** [donet5/SqlSugar#956]
数据库表的某个字段要经过函数转换才是其真实值
如` select Sf_Translate(IdCard, IdType) IdCard from Employee`
我尝试过用`ConfigureExternalServices.EntityService`修改了DbColumnName 然后在‘AopEvents.OnExecutingChangeSql’修改语句去掉引号，但是查询出来的实体的IdCard的值是null的。
有什么好的实现方法吗？

**Comment by donet5** [comment]
IdCard =SqlFunc.MappingColumn(default(string), "Sf_Translate(IdCard, IdType)")
