### ISSUE TITLE
实体是不是不支持Guid/Guid?类型

### ISSUE THREAD

**Issue by victor596** [donet5/SqlSugar#957]
当我定义了一个Guid类型使用Queryable 时出错
SqlSugar.SqlSugarException : English Message : Entity mapping error.将字符串转换为 uniqueidentifier 时失败。
    Chinese Message : 实体与表映射出错。将字符串转换为 uniqueidentifier 时失败。

**Comment by donet5** [comment]
这要看你数据库是什么类型 ，你这个错是 数据库的字会串转 GUID失败

**Comment by donet5** [comment]
长时间没回复先关闭了，有问题重新发 ISSUEES
