### ISSUE TITLE
当使用多个Mapper时，只生效最后一个Mapper

### ISSUE THREAD

**Issue by 1093439315** [donet5/SqlSugar#961]
Sqlsugar version: SqlSugarCore 5.0.4
Env: sqllite or mysql(其他数据库没试过)
只执行了最后一个mapper

```
       var result = db.Queryable<Student>()
                .Mapper((it, cache) =>
                {
                    it.Name = "11";
                    it.SchoolId = 3;
                })
                .Mapper((it, cache) =>
                {
                    it.Name = "22";
                })
                .ToList();
```
   
   
```
    public class Student
    {
        [SugarColumn(IsPrimaryKey = true, IsIdentity = true)]
        public int Id { get; set; }
        public int? SchoolId { get; set; }
        public string Name { get; set; }
    }
```
   @donet5

**Comment by donet5** [comment]
var result = db.Queryable<Order>()
            .Mapper((it) =>
            {
                it.Name = "11";
                it.Price = 3;
            })
            .Mapper((it) =>
            {
                it.Name = "22";
            })
            .ToList();
带cache的重载确实只生效了一次，你可以先用不带cache的重载

**Comment by donet5** [comment]
本地已修复了，后会一个月内会发布的
