### ISSUE TITLE
如何手动指定 DbConnection对象？

### ISSUE THREAD

**Issue by John0King** [donet5/SqlSugar#963]
在跟现有系统公用的时候， 原系统已经有一套 connection 管理， 我的需求是， sqlsugar不能自己创建自己的 `IDbConnection`对象， 必须使用我指定的 connection

**Comment by donet5** [comment]
db.ado.connection=你的对象试试

**Comment by John0King** [comment]
@donet5  另外sqlsugar 里面有 master-slave 多链接， 读写分离，设置这个会管用么？ 而且我想不给初始化的 sql 链接参数，阻止sqlsugar 自己启用自己的Connection，防止连接池的资源被提前用完

**Comment by donet5** [comment]
读写分模式你处理不了，不读写分离你是可以直接指定的

**Comment by John0King** [comment]
我想知道的是， 这个 SqlSugarClient 是否会从开始就打开一个 connection （毕竟构造函数要了连接字符串） ,      我担心它浪费连接池资源

**Comment by donet5** [comment]
不会占用，只有OPEN状态才会占连接池

**Comment by donet5** [comment]
没有OPEN只是一个C#对象

**Comment by donet5** [comment]
还有没有疑问，没疑问我就关了
