### ISSUE TITLE
你的官方文档的updateable方法示例有问题。！！！

### ISSUE THREAD

**Issue by wang2650** [donet5/SqlSugar#968]
文档是这样写的<html>

var result= db.Updateable<Student>().SetColumns(it => new Student() { Name = "a", CreateTime = DateTime.Now }).Where(it => it.Id == 11).ExecuteCommand();

我按上面的写  提示错误：
: 根据对像更新 db.Updateabe(对象) 禁止使用 SetColumns和Where ,你可以使用WhereColumns 和  UpdateColumns。 更新分为2种方式 1.根据表达式更新 2.根据实体或者集合更新 ， 具体用法请查看文档 
Chinese Message :  no support SetColumns and Where
我用的是5.0.4.2版本。

**Comment by donet5** [comment]
错误提示很明显了 ， Updateable(无参数) 才能用setcolumns

**Comment by donet5** [comment]
你的代码肯定是 db.updateable(对象) .SetColumns

**Comment by wang2650** [comment]
我的锅，不好意思。
