### ISSUE TITLE
Demo异步返回类型引用有误

### ISSUE THREAD

**Issue by SherryShi0108** [donet5/SqlSugar#969]
https://github.com/donet5/SqlSugar/blob/094c75ed2f534e5e82727fda725743b0672555bd/Src/Asp.Net/PgSqlTest/Demo/Demo0_SqlSugarClient.cs#L327

Maybe:

` if (result2.Result.IsSuccess == false)`

看了下好像所有Demo中的事务用法这里都写错了~

**Comment by donet5** [comment]
是写错了OK我会改掉

**Comment by donet5** [comment]
更新过了，以前后异步事务用例也是错的

**Comment by donet5** [comment]
var result2 = db.UseTranAsync(async () =>
            {

                db.ChangeDatabase("1");//use db1
                await db.Deleteable<Order>().ExecuteCommandAsync();
                Console.WriteLine("---Delete all " + db.CurrentConnectionConfig.DbType);
                Console.WriteLine(db.Queryable<Order>().Count());

                db.ChangeDatabase("2");//use db2
                await db.Deleteable<Order>().ExecuteCommandAsync();
                Console.WriteLine("---Delete all " + db.CurrentConnectionConfig.DbType);
                Console.WriteLine(db.Queryable<Order>().Count());
                throw new Exception("");

            });
