### ISSUE TITLE
建议针对个别数据库类型重写Any方法，优化查询。

### ISSUE THREAD

**Issue by dodle** [donet5/SqlSugar#970]
使用Any判断记录是否存在，看代码发现是通过Count()>0来实现的，建议针对MySql、SqlServer、PostgreSql、SQLite这4类数据库进行重现优化。
MySql、SQLite写法：
`SELECT EXISTS (SELECT 1 FROM table WHERE field = 'value')`
SqlServer写法：
`IF EXISTS (SELECT 1 FROM table WHERE field = 'value') SELECT 1 ELSE SELECT 0`
PostgreSql写法：
`SELECT CASE WHEN EXISTS(SELECT 1 FROM table WHERE field = 'value') THEN 1 ELSE 0 END`

最后直接判断查询的值是否等于1即可。

**Comment by donet5** [comment]
意义不大吧，COUNT在有条件情况下性能并不差

**Comment by donet5** [comment]
(SELECT COUNT(1) FROM table WHERE field = 'value')>0  这是目前逻辑

**Comment by donet5** [comment]
就算是分页没条件一二万的COUNT也是很快的，何况有条件的直接走索引过滤

**Comment by donet5** [comment]
可以去SQLSERVER执行计划比较

select count(1) from [dbo].[Order] where id>0
IF EXISTS (SELECT 1 FROM [dbo].[Order] WHERE id>0) SELECT 1 ELSE SELECT 0

2者基本相同有条件过滤情况下

**Comment by donet5** [comment]
算了我还是优化一下吧 ，比你的exists方便多了

 select  top 1  1  from  table   WHERE field = 'value'

**Comment by dodle** [comment]
> 算了我还是优化一下吧 ，比你的exists方便多了
> 
> select top 1 1 from table WHERE field = 'value'

又学到另一种写法了。只是假如没有匹配数据时返回0行，需要在代码里面判断是否NULL。

**Comment by donet5** [comment]
有现成的方法

**Comment by donet5** [comment]
验证一下NULL就行了

**Comment by donet5** [comment]
本地已经优化，近期同步
