### ISSUE TITLE
DbColumnInfo里没是否虚拟列的判断吗?

### ISSUE THREAD

**Issue by jiushi97** [donet5/SqlSugar#971]
需要根据这个判断来给实体加上IsOnlyIgnoreInsert = true,IsOnlyIgnoreUpdate = true

**Comment by donet5** [comment]
IsIgnore 就是虚拟列

**Comment by donet5** [comment]
IsOnlyIgnoreInsert = true,IsOnlyIgnoreUpdate = true  这2个是更新和插入 的忽略

**Comment by jiushi97** [comment]
我是需要这样
if(DbColumnInfo.IsVirtual){
     自己写的实体生成.Append("[SugarColumn(IsOnlyIgnoreInsert =true,IsOnlyIgnoreUpdate =true)]");
}
但是没有这个判断，目前是在ColumnDescription里加了关键字来生成的:
if(DbColumnInfo.ColumnDescription.Contains("Virtual")){
     自己写的实体生成.Append("[SugarColumn(IsOnlyIgnoreInsert =true,IsOnlyIgnoreUpdate =true)]");
}

**Comment by donet5** [comment]
DbFirst肯定不行
