### ISSUE TITLE
`ToPageList`  里面的第一个参数， 最好不叫  pageIndex

### ISSUE THREAD

**Issue by John0King** [donet5/SqlSugar#973]
## description

C# 所有的索引都是从0开始，  而分页同理是从0开始的，  而分页**显示**的页码是从1开始的， 这里就有一个混淆：
我们传递的到底是  index （从0开始的） 还是页码（number，从1开始的） ，
在这里 SqlSugar 确实要求传递的是 页码 ， 而不是索引值，  但是名字极其仍然容易混淆 `pageIndex` , 乍一看是要求传递索引值，
但其实并不是。

我建议将该参数改名为  `pageNumber`  ,

这里附上我的 PageRequestBase 基类的处理

```C#
    /// <summary>
    /// 分页基类
    /// </summary>
    public class PagedRequestBase
    {
        /// <summary>
        /// 分页页码
        /// </summary>
        public virtual int PageNumber
        {
            get
            {
                return PageIndex + 1;
            }
            set
            {
                PageIndex = value < 1 ? 0 : value - 1;
            }
        }

        /// <summary>
        /// 分页索引
        /// </summary>
        public virtual int PageIndex { get; set; } = 0;

        /// <summary>
        /// 页大小
        /// </summary>
        public virtual int PageSize { get; set; } = 20;
    }
```

---------------------------------

需要注意的是，  更改方法的 参数名 是一个  source 级别的 breaking-change   eg:

```C#
query.ToPageList(pageIndex: 1, pageSize:2, ref total);  //breaking

query.ToPageList(1,2,ref total);  // non-breaking

```

**Comment by donet5** [comment]
这个我问一下大家喜欢哪个名字

**Comment by donet5** [comment]
number对于我个人而言 和size容易混淆

**Comment by John0King** [comment]
`number` 代表数字，   `size` 代表大小  ， 你怎么会混淆这两个？ 🤣

**Comment by donet5** [comment]
分页数字  ：   是第几页，还是总共几页   还是有点绕的

**Comment by John0King** [comment]
总共有几页:  `MaxPage`    `PageCount`

 和 总数  `TotalItems`  `TotalCount`  `Total`

分页页码： `PageNumber`  `Page`
分页索引 ：  `PageIndex`   `Page`
当前页：  `CurrentPage`  `CurrentPageNumber`  当前索引 `CurrentPageIndex`
分页大小 : `PageSize`
分页控件大小： `MaxPagerItems`

虽然没什么标准， 但是基本上 在分页以页为方式的分页上，  PageSize   PageNumber/PageIndex  基本上算是个标准了，  Index 不管在什么情况下 都应该从0开始，  除非是 VBS 等索引从1开始的语言

**Comment by donet5** [comment]
后面会修改

**Comment by donet5** [comment]
已经优化
