### ISSUE TITLE
SugarIoc 怎么设置 ConnectionConfig 中的MoreSetting

### ISSUE THREAD

**Issue by zanderzhg** [donet5/SqlSugar#978]
SugarIoc 怎么设置 ConnectionConfig 中的MoreSetting

**Comment by donet5** [comment]
Services.ConfigurationSugar(db =>
 {
      db.CurrentConnectionConfig.MoreSetting=new MoreSetting(){}
      db.Aop.xxx
  });

**Comment by zanderzhg** [comment]
谢谢.
