### ISSUE TITLE
PgSql14复合主键CodeFirst问题

### ISSUE THREAD

**Issue by zanderzhg** [donet5/SqlSugar#981]
```csharp
public class RoleMenuEntity
{
    [SugarColumn(IsPrimaryKey = true)]
    public long RoleId { get; set; }

    [SugarColumn(IsIgnore = true)]
    public virtual RoleEntity? Role { get; set; }

    [SugarColumn(IsPrimaryKey = true)]
    public long MenuId { get; set; }

    [SugarColumn(IsIgnore = true)]
    public virtual MenuEntity? Menu { get; set; }
}
```
没有表时第一次创建没问题，第二次实体也没变动，提示 `RoleMenuEntity 创建失败,请认真检查 1、属性需要get set 2、特殊类型需要加Ignore 具体错误内容： 不支持修改多主键表，请删除表在创建`

**Comment by donet5** [comment]
这个有点头痛，因为查不出第二个主键 ，你可以先用CodeFirst禁止更新模式
主要是下面SQL查不出2个主键 ，如果你能想到办法我这边能更快解决
`select cast (pclass.oid as int4) as TableId,cast(ptables.tablename as varchar) as TableName,
                                pcolumn.column_name as DbColumnName,pcolumn.udt_name as DataType,
                                CASE WHEN pcolumn.numeric_scale >0 THEN pcolumn.numeric_precision ELSE pcolumn.character_maximum_length END   as Length,
                                pcolumn.column_default as DefaultValue,
                                pcolumn.numeric_scale as DecimalDigits,
                                pcolumn.numeric_scale as Scale,
                                col_description(pclass.oid, pcolumn.ordinal_position) as ColumnDescription,
                                case when pkey.colname = pcolumn.column_name
                                then true else false end as IsPrimaryKey,
                                case when pcolumn.column_default like 'nextval%'
                                then true else false end as IsIdentity,
                                case when pcolumn.is_nullable = 'YES'
                                then true else false end as IsNullable
                                 from (select * from pg_tables where upper(tablename) = upper('{0}') and schemaname='public') ptables inner join pg_class pclass
                                on ptables.tablename = pclass.relname inner join (SELECT *
                                FROM information_schema.columns
                                ) pcolumn on pcolumn.table_name = ptables.tablename
                                left join (
	                                select  pg_class.relname,pg_attribute.attname as colname from 
	                                pg_constraint  inner join pg_class 
	                                on pg_constraint.conrelid = pg_class.oid 
	                                inner join pg_attribute on pg_attribute.attrelid = pg_class.oid 
	                                and  pg_attribute.attnum = pg_constraint.conkey[1]
	                                inner join pg_type on pg_type.oid = pg_attribute.atttypid
	                                where pg_constraint.contype='p'
                                ) pkey on pcolumn.table_name = pkey.relname
                                order by ptables.tablename`

**Comment by donet5** [comment]
上面的语句 upper('{0}')  换成 upper('表名')

**Comment by donet5** [comment]
已经找到方案了 近2天同步到GITHUB
