### ISSUE TITLE
enum 转换兼容错

### ISSUE THREAD

**Issue by nappinglady** [donet5/SqlSugar#983]
![image](https://user-images.githubusercontent.com/5546223/147625170-7cde242e-16f1-47b3-90dd-97a687893e21.png)

**Comment by donet5** [comment]
修复了

**Comment by nappinglady** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
