### ISSUE TITLE
使用DataReader实现DataAdapter的Fill方法数据行状态有些问题

### ISSUE THREAD

**Issue by xsonik** [donet5/SqlSugar#984]
正常获取DataSet或DataTable类型的数据源时，行状态为DataRowState.Unchanged。
DataExtensions.cs实现的DataAdapter中的Fill方法填充的行状态为DataRowState.Added。
获取数源后用户需要额外的执行AcceptChanges()

**Comment by donet5** [comment]
你能描述一下这个东西有什么用吗？

**Comment by xsonik** [comment]
DataTab做为一个数据源，用户对数据进行操作时(不仅是查看)，就会用DataRowState来判断哪些行是添加/修改/删除/未变更。然后执行对应的保存或其它逻辑。

**Comment by donet5** [comment]
dt.AcceptChanges() 我返回时加上这个代码就行了是吗？

**Comment by xsonik** [comment]
是的DataReader读取填充完成后加dt.AcceptChanges()

**Comment by donet5** [comment]
OK 今天晚上同步代码到GITHUB

**Comment by donet5** [comment]
源码已更新 ，有问题重新发贴
