### ISSUE TITLE
DbFirstTemplate生成格式

### ISSUE THREAD

**Issue by CyouRin** [donet5/SqlSugar#987]
DbFirstTemplate.cs 中
PropertyTemplate字符串的{SugarColumn} 与 public ...{get set} 同样使用`PropertySpace`拼接
生成，但是生成的文件中格式不对应
[SugarColumn]前11空格， 符合PropertySpace
public ...{get set} 前8个空格，符合正常编码规约
这种情况下，每次生成结束还需格式化调整[SugarColumn]前空格数量
如何做能使[SugarColumn]与public对齐，实现符合代码规约的形式（两个TAB（八位字符））

**Comment by donet5** [comment]
近期会修复

**Comment by donet5** [comment]
我看了没什么问题设计是这样的，并没有让你精准到每个空格 ,.SettingPropertyDescriptionTemplate(old 这个old复制出来改一下就行了 old有空格那你复制出来的也就是有空格的

**Comment by donet5** [comment]
`   .SettingPropertyDescriptionTemplate(old =>
                        {
                            return @"           /// <summary>
                          /// Desc_New:{PropertyDescription}
                          /// Default_New:{DefaultValue}
                                /// Nullable_New:{IsNullable}
                                /// </summary>";
                        })`
复制出来是什么样就改什么样

**Comment by CyouRin** [comment]
不是这个方法，是SettingPropertyTemplate 在这个方法中有个{SugarColumn} 这个是控制属性上面[]位置的，  
但这个方法中{SugarColumn} 的前面已经没有空格，生成出的内容与属性定义关键字、注释/// 等相差三个空格，
给您发个例子您看一下 
```   
        /// <summary>  
        /// 版本号  
        /// </summary>  
           [SugarColumn(ColumnName="VERSION")]  
        public int? Version { get; set; }  
```
这是生成出的结果，但希望的效果如下：  
```   
        /// <summary>  
        /// 版本号  
        /// </summary>  
        [SugarColumn(ColumnName="VERSION")]  
        public int? Version { get; set; }  
```
简单查了一下，发现是您原模板替换{SugarColumn}时在前方加了一些空格导致这种情况，请问是否有办法做出一些调整

**Comment by donet5** [comment]
old=> 把这个old复制出来改一下就行了 , old 有几个空格你就扔几个空格

**Comment by donet5** [comment]
你可以看默认生成出来是对齐的
