### ISSUE TITLE
更新 System.Data.Sqlite版本

### ISSUE THREAD

**Issue by MetaMagicYang** [donet5/SqlSugar#988]
SQLite Team 在 nuget 上发布了 1.0.115.5 版本包，可否更新 SqlSugar 包引用，也不需要手动在发布文件夹拷贝 SQLite.Interop.dll

**Comment by donet5** [comment]
sqlsugar一直支持新版本的 System.Data.Sqlite  ，nuget先安装sqlsugar然后在安装 System.Data.Sqlite ， 如果还报错在发布层 也安装一下先装SQLSUGAR

**Comment by MetaMagicYang** [comment]
我在项目中使用ReferencePackage方式进行引用管理，通过nuget添加新版 System.Data.SQLite 包引用后，会始终提示版本冲突。重新卸载再安装也没能解决问题。
![image](https://user-images.githubusercontent.com/96125782/149141378-e8363321-735d-4718-8b1e-23fb4bc078c6.png)

**Comment by donet5** [comment]
错误上面连教程都有了，按错误提示操作就行了

**Comment by MetaMagicYang** [comment]
一直以为包管理会自动解决版本冲突的问题，看来还是需要在配置文件进行手动配置

<Target Name="ForceGenerationOfBindingRedirects"
          AfterTargets="ResolveAssemblyReferences"
          BeforeTargets="GenerateBindingRedirects"
          Condition="'$(AutoGenerateBindingRedirects)' == 'true'">
    <PropertyGroup>
      <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    </PropertyGroup>
  </Target>
