### ISSUE TITLE
逻辑删除增加一个参数

### ISSUE THREAD

**Issue by 66damon66** [donet5/SqlSugar#989]
逻辑删除能否增加一个参数，目前看了下源码，默认是bool类型的，烦请增加一个参数，可能我逻辑删除栏位是int或者string类型的，所对应的逻辑删除值能够自己传入
谢谢

**Comment by donet5** [comment]
好的后面优化关注 https://www.donet5.com/Home/Doc?typeId=1213

**Comment by donet5** [comment]
ExecuteCommand(string LogicFieldName = null,object deleteValue=null,string deleteTimeFieldName = null)
 1. LogicFieldName(逻辑删除列，默认等于isdeleted)
 2. deleteValue (默认是true为删除值 )  
 3. deleteTimeFieldName（删除时间列，指定后删除时会更新成当前时间）

**Comment by donet5** [comment]
这个重载丰富了一下 ，近期会同步

**Comment by kuangshp** [comment]
DeleteTimeFieldName有使用案例吗
