### ISSUE TITLE
where条件含三元表达式后排序会报空指针

### ISSUE THREAD

**Issue by lishuo0710** [donet5/SqlSugar#991]
重現方式：
```
   var  IsDeptManage = false;//方法傳參
   var deptNo = "";//方法傳參  
   var compacts = _compactRepository.Table.Where(o => o.OrganizationId == organizationId && o.ParentId == 0);
   compacts = compacts.Where(c=> IsDeptManage ? c.DeptNo.Contains(deptNo) : c.Creator == userId);
   var result= compacts.OrderByDescending(x => x.Id).ToList();//空指針
```

**Comment by donet5** [comment]
先用 sqlfunc.if   when case写法 ，

**Comment by donet5** [comment]
c.Creator == userId 作为值可能解析不了，后面我在想办法优化

**Comment by donet5** [comment]
.WhereIF(c=> IsDeptManage , c.DeptNo.Contains(deptNo))
.WhereIF(c=> IsDeptManage ==false, c.Creator == userId) 这样也行

**Comment by donet5** [comment]
compacts.OrderByDescending(x => x.Id).ToList()    你这个代码并不 sqlsugar 我测试过了会报 参数类型不支持

queryable并没有 OrderByDescending 方法

**Comment by lishuo0710** [comment]
OrderByDescending 属于linq，我已经将这段历史代码调整成if了。谢谢回复。
