### ISSUE TITLE
关于这个orm，不知道是我不会用还是确实不够人性化

### ISSUE THREAD

**Issue by kensmaster** [donet5/SqlSugar#992]
1.我用freesql生成表，没设置属性允许null，默认不会设定字段不允许null
而sqlsuagr创建的表字段居然是非null的，瞬间就不友好了

使用SqlSugarDb.Insertable<UsersNew>(m).IgnoreColumns(ignoreNullColumn: true).ExecuteCommand()也没用
依然提示 某些列必须插入值。。。

2.另外创建数据库表也是个问题：居然没得选择是否统一根据实体字段来创建表字段
我用的postgresSQL数据库，，实体字段都是C#驼峰命名，而数据库全小写了，唉无语

**Comment by donet5** [comment]
1. 第一点只是默认值不一样，在很多数据库设计中是不允许出现NULL的， 你可以用实体AOP全局处理 
2. 第二点应该是优点 postgresSQL  数据小写才是规范 ， 这样你写sql语句可以无视大小写

**Comment by donet5** [comment]
https://www.donet5.com/Home/Doc?typeId=1221  
 sqlsugar  CURD功能 支持了规范表和不规范表
 
codefirst只支持了规范表

**Comment by donet5** [comment]
PGSQL建表规范：对象名（表名、列名、函数名、视图名、序列名、等对象名称）规范，对象名务必只使用小写字母，下划线，数字。不要以pg开头，不要以数字开头，不要使用保留字

https://www.cnblogs.com/panpanwelcome/p/12430122.html

**Comment by donet5** [comment]
自动处理nullable   int? string? 这种就可以生成对应的可空类型
 
var db= new SqlSugarClient(new ConnectionConfig()
            {
                DbType = SqlSugar.DbType.SqlServer,
                ConnectionString = Config.ConnectionString,
                IsAutoCloseConnection = true,
                ConfigureExternalServices=new ConfigureExternalServices {
                    EntityService = (c, p) => 
                    {
                        if (c.PropertyType.IsGenericType && c.PropertyType.GetGenericTypeDefinition() == typeof(Nullable<>)) 
                        {
                            p.IsNullable = true;
                        } 
                    }
                }
            });
