### ISSUE TITLE
MySQL 使用批量插入、更新方法，datetime插入更新为null

### ISSUE THREAD

**Issue by linking123** [donet5/SqlSugar#993]
使用 大数据写入、更新，https://www.donet5.com/home/Doc?typeId=2404
```
db.Fastest<RealmAuctionDatum>().BulkCopy(GetList());
db.Fastest<RealmAuctionDatum>().BulkUpdate(GetList());
```

数据可以插入、更新；只是 datetime无法插入，原有datetime的字段更新为null；

请问有没有遇到过此问题，还是我的配置问题

**Comment by donet5** [comment]
[https://www.donet5.com/Home/Doc?typeId=2366](https://www.donet5.com/Home/Doc?typeId=2366) 按这个模版写个用例给我

**Comment by linking123** [comment]
@donet5 感谢回复

# 用例代码

```[HttpGet]
public object Get()
{
    var db=new  SqlSugarScope(new SqlSugar.ConnectionConfig() {
        ConnectionString = "server=.;uid=sa;pwd=sasa;database=SQLSUGAR4XTEST",
        DbType = DbType.MySql,
        InitKeyType = InitKeyType.Attribute,
        IsAutoCloseConnection = true
    });
 
 	List<Test001> list = new();
 
    //用例代码 
    var result = db.Fastest<Test001>().BulkCopy(list); //or
    //db.Fastest<Test001>().BulkUpdate(list);  

    return result;
}

//用例实体
public class Test001 
{
    [SugarColumn(ColumnName = "id", IsPrimaryKey = true, IsIdentity = true)]
    public int Id { get; set; }
    
    [SugarColumn(ColumnName = "create_time")]
	public DateTime CreateTime { get; set; }
}
```



# 版本信息

- MySQL：5.6
- SqlSugar：5.0.5.4



# 现象

- 插入或更新，`DateTime` 类型字段为 `NULL`，其他类型字段正常

**Comment by linking123** [comment]
更新测试过程、现象；尚未找到原因

# 现象

- 错误：项目代码使用大数据方式插入或更新，`DateTime` 类型字段为 `NULL`，其他类型字段正常；使用原有api如`Storageable.AsInsertable`正常插入
- 官网下载源码
  - 单独新建database或用原有database，跑单元测试，成功
  - 未见到特殊设置
- 奇异：同事电脑以及测试环境，跑的没问题；怀疑是自己电脑设置的时区问题
  - 本机环境：
    - 时间: utc+8 beijing
    - 地区: hongkong
    - regional format: usa
    - 语言：english(usa)
- 修改本机环境为大陆、中文，测试项目代码， `DateTime` 成功插入
- 将系统还原为原测试环境后，源码单元测试没问题，只单单项目代码有问题

**Comment by donet5** [comment]
```cs

    //用例实体
    public class UnitTest001
    {
        [SugarColumn(ColumnName = "id", IsPrimaryKey = true, IsIdentity = true)]
        public int Id { get; set; }

        [SugarColumn(ColumnName = "create_time",IsNullable =true)]
        public DateTime? CreateTime { get; set; }
    }
```
经过测试没问题

server=localhost;Database=SqlSugar4xTest;Uid=root;Pwd=haosql; AllowLoadLocalInfile=true;Allow Zero Datetime=True;Convert Zero Datetime=True

**Comment by donet5** [comment]
连接字符串和实体和你的有区别

**Comment by donet5** [comment]
还有问题吗

**Comment by linking123** [comment]
作者辛苦了，年假期间缺乏工作环境，待我明天回归工作岗位测试一下，再回复好吗？

**Comment by donet5** [comment]
源码版本高于NUGET版本

**Comment by linking123** [comment]
1.在源码的单元测试中，已测试插入原表，成功。（如是，则下一版本应解决问题了）

2.尚未测试编译源码作为dll依赖在自己的项目中使用（待学习），todo

**Comment by donet5** [comment]
源码ok 就行
