### ISSUE TITLE
关于 ‘差异日志功能’ 的询问

### ISSUE THREAD

**Issue by xulei-Itachi** [donet5/SqlSugar#995]
对于 EnableDiffLogEvent 方法，如何实现为 对某个 实体，或者某个仓储 进行统一的启用，或者停用管控，而不是要在进行update操作的时候，需要认为调用？
类似于这样
[AlwaysEnableDiffLogEvent(true)]
class Table A
{
}
或者
TableARepository.AlwaysEnableDiffLogEvent = true;

**Comment by donet5** [comment]
未知性的东西太多了，我这边不太好封装，像你这种特定需求自个封装很简单

**Comment by donet5** [comment]
先关闭了还有疑问发新issue
