### ISSUE TITLE
连接mariadb 10.7.3发生错误。

### ISSUE THREAD

**Issue by haijunluo** [donet5/SqlSugar#997]
//如果不存在就创建， 不存在就略过
            sqlSugar.DbMaintenance.CreateDatabase(); //创建数据库

The given key '25960' was not present in the dictionary.

**Comment by donet5** [comment]
sqlSugar.Open() 看能不能执行，如果这个可以执行就可以用

sqlsugar 操作MSYSQL有2个不同的驱动版本  mysql.data和 mysqlConnector

**Comment by donet5** [comment]
先关闭有问题重新发贴
