### ISSUE TITLE
达梦数据库字段大小写问题

### ISSUE THREAD

**Issue by PauloChina** [donet5/SqlSugar#998]
实体属性名为小写，数据库表字段名也是小写，但是查询SQL默认表和字段为大写
为什么不能像PGSQL一样可以在配置里面设置AutoToUpper呢

**Comment by donet5** [comment]
主要用户太少了，并且按数据库规范建表没什么不好，为什么要搞小写

**Comment by PauloChina** [comment]
> 

历史项目，要支持多数据库，调整起来影响太大了

**Comment by donet5** [comment]
只要不是老库就不麻烦，数据库规范，实体大小写都可以查的

**Comment by donet5** [comment]
也就是 实体是  Student 那么  PGSQ可以存  student    MSSQL可以存 Student  ORACLE可以存 STUDENT

**Comment by donet5** [comment]
把这个添加到到了需求列表 ，https://www.donet5.com/Home/Doc?typeId=1213  如果需求多后续会开发
